//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KfAccountNumbers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KfAccountNumbers.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string CaSinEmpty {
            get {
                return ResourceManager.GetString("CaSinEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number must only contain digit characters (0-9) in non-separator character locations.
        /// </summary>
        internal static string CaSinInvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("CaSinInvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number contains an invalid check digit.
        /// </summary>
        internal static string CaSinInvalidCheckDigit {
            get {
                return ResourceManager.GetString("CaSinInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number must have length 9 (digits only) or 11 (9 digits with two separator characters).
        /// </summary>
        internal static string CaSinInvalidLength {
            get {
                return ResourceManager.GetString("CaSinInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number may not have a leading digit (the province indicator) of zero (0) or eight (8).
        /// </summary>
        internal static string CaSinInvalidProvince {
            get {
                return ResourceManager.GetString("CaSinInvalidProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number with length 11 contains an unexpected character at a separator position.
        /// </summary>
        internal static string CaSinInvalidSeparatorEncountered {
            get {
                return ResourceManager.GetString("CaSinInvalidSeparatorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateResult Failure error may not be null.
        /// </summary>
        internal static string CreateResultErrorNull {
            get {
                return ResourceManager.GetString("CreateResultErrorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateResult Success value may not be null.
        /// </summary>
        internal static string CreateResultValueNull {
            get {
                return ResourceManager.GetString("CreateResultValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string DescriptionEmpty {
            get {
                return ResourceManager.GetString("DescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK Personnummer may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string DkPersonnummerEmpty {
            get {
                return ResourceManager.GetString("DkPersonnummerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK Personnummer contains a non-digit character where a digit was expected.
        /// </summary>
        internal static string DkPersonnummerInvalidCharacter {
            get {
                return ResourceManager.GetString("DkPersonnummerInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK Personnummer requires a valid six digit date of birth (DDMMYY) format in character positions 0-5 (zero-based).
        /// </summary>
        internal static string DkPersonnummerInvalidDateOfBirth {
            get {
                return ResourceManager.GetString("DkPersonnummerInvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK Personnummer must have length 10 (no separator character) or 11 (separator character).
        /// </summary>
        internal static string DkPersonnummerInvalidLength {
            get {
                return ResourceManager.GetString("DkPersonnummerInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK Personnummer separator character must be a dash (&apos;-&apos;).
        /// </summary>
        internal static string DkPersonnummerInvalidSeparator {
            get {
                return ResourceManager.GetString("DkPersonnummerInvalidSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI Henkilotunnus may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string FiHenkilotunnusEmpty {
            get {
                return ResourceManager.GetString("FiHenkilotunnusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI Henkilotunnus has an invalid century indicator in character position 6 (zero-based).
        /// </summary>
        internal static string FiHenkilotunnusInvalidCenturyIndicator {
            get {
                return ResourceManager.GetString("FiHenkilotunnusInvalidCenturyIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI Henkilotunnus contains a non-digit character in the date of birth or individual number elements.
        /// </summary>
        internal static string FiHenkilotunnusInvalidCharacter {
            get {
                return ResourceManager.GetString("FiHenkilotunnusInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI Henkilotunnus must have a valid modulus 31 check character in the trailing (right-most) position.
        /// </summary>
        internal static string FiHenkilotunnusInvalidCheckDigit {
            get {
                return ResourceManager.GetString("FiHenkilotunnusInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI Henkilotunnus requires a valid six digit date of birth (DDMMYY) format in character positions 0-5 (zero-based).
        /// </summary>
        internal static string FiHenkilotunnusInvalidDateOfBirth {
            get {
                return ResourceManager.GetString("FiHenkilotunnusInvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI Henkilotunnus may not have an individual number less than &quot;002&quot; in character positions 7-9 (zero-based).
        /// </summary>
        internal static string FiHenkilotunnusInvalidIndividualNumber {
            get {
                return ResourceManager.GetString("FiHenkilotunnusInvalidIndividualNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI Henkilotunnus must have length 11.
        /// </summary>
        internal static string FiHenkilotunnusInvalidLength {
            get {
                return ResourceManager.GetString("FiHenkilotunnusInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String formatting mask may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string FormatMaskEmpty {
            get {
                return ResourceManager.GetString("FormatMaskEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to format with a mask may not be null.
        /// </summary>
        internal static string FormatStrNull {
            get {
                return ResourceManager.GetString("FormatStrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Kennitala may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string IsKennitalaEmpty {
            get {
                return ResourceManager.GetString("IsKennitalaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Kennitala century indicator must be either &apos;9&apos; or &apos;0&apos;.
        /// </summary>
        internal static string IsKennitalaInvalidCentury {
            get {
                return ResourceManager.GetString("IsKennitalaInvalidCentury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Kennitala contains a non-digit character where a digit was expected.
        /// </summary>
        internal static string IsKennitalaInvalidCharacter {
            get {
                return ResourceManager.GetString("IsKennitalaInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Kennitala must have a valid check digit character in the second character from the right of the value.
        /// </summary>
        internal static string IsKennitalaInvalidCheckDigit {
            get {
                return ResourceManager.GetString("IsKennitalaInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Kennitala requires a valid six digit date of birth (DDMMYY) format in character positions 0-5 (zero-based).
        /// </summary>
        internal static string IsKennitalaInvalidDateOfBirth {
            get {
                return ResourceManager.GetString("IsKennitalaInvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Kennitala must have length 10 (no separator character) or 11 (separator character).
        /// </summary>
        internal static string IsKennitalaInvalidLength {
            get {
                return ResourceManager.GetString("IsKennitalaInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS Kennitala separator character must not be a digit.
        /// </summary>
        internal static string IsKennitalaInvalidSeparator {
            get {
                return ResourceManager.GetString("IsKennitalaInvalidSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX CURP may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string MxCurpEmpty {
            get {
                return ResourceManager.GetString("MxCurpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX CURP requires alphabetic characters in positions 0-3 and 13-15 (zero-based).
        /// </summary>
        internal static string MxCurpInvalidAlphabeticCharacterEncountered {
            get {
                return ResourceManager.GetString("MxCurpInvalidAlphabeticCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX CURP requires a digit character in character position 17 (zero-based). This is the check digit assigned by RENAPO.
        /// </summary>
        internal static string MxCurpInvalidCheckDigit {
            get {
                return ResourceManager.GetString("MxCurpInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX CURP requires valid six digit date of birth (YYMMDD) in character positions 4-9 (zero-based).
        /// </summary>
        internal static string MxCurpInvalidDateOfBirth {
            get {
                return ResourceManager.GetString("MxCurpInvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX CURP requires a gender code of H (Hombre), M (Mujer) or X (non-binary) in character position 10 (zero-based).
        /// </summary>
        internal static string MxCurpInvalidGender {
            get {
                return ResourceManager.GetString("MxCurpInvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX CURP requires an alphanumeric character in character position 16 (zero-based). This is the homoclave character assigned by RENAPO.
        /// </summary>
        internal static string MxCurpInvalidHomoclave {
            get {
                return ResourceManager.GetString("MxCurpInvalidHomoclave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX CURP must have length 18.
        /// </summary>
        internal static string MxCurpInvalidLength {
            get {
                return ResourceManager.GetString("MxCurpInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX CURP requires a valid two letter state code in character positions 11-12 (zero-based).
        /// </summary>
        internal static string MxCurpInvalidState {
            get {
                return ResourceManager.GetString("MxCurpInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Burgerservicenummer may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string NlBurgerservicenummerEmpty {
            get {
                return ResourceManager.GetString("NlBurgerservicenummerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Burgerservicenummer contains a non-digit character where a digit was expected.
        /// </summary>
        internal static string NlBurgerservicenummerInvalidCharacter {
            get {
                return ResourceManager.GetString("NlBurgerservicenummerInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Burgerservicenummer must have a valid modulus 11 (11-proef) check digit in the trailing (right-most) position.
        /// </summary>
        internal static string NlBurgerservicenummerInvalidCheckDigit {
            get {
                return ResourceManager.GetString("NlBurgerservicenummerInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Burgerservicenummer must have length 9 (without separator characters) or 11 (with separator characters).
        /// </summary>
        internal static string NlBurgerservicenummerInvalidLength {
            get {
                return ResourceManager.GetString("NlBurgerservicenummerInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL Burgerservicenummer separator character may not be a digit and the same non-digit character must be present in both separator character locations.
        /// </summary>
        internal static string NlBurgerservicenummerInvalidSeparator {
            get {
                return ResourceManager.GetString("NlBurgerservicenummerInvalidSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Foedselsnummer may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string NoFoedselsnummerEmpty {
            get {
                return ResourceManager.GetString("NoFoedselsnummerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Foedselsnummer contains a non-digit character where a digit was expected.
        /// </summary>
        internal static string NoFoedselsnummerInvalidCharacter {
            get {
                return ResourceManager.GetString("NoFoedselsnummerInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Foedselsnummer must have two valid check digit characters in the trailing (right-most) positions.
        /// </summary>
        internal static string NoFoedselsnummerInvalidCheckDigits {
            get {
                return ResourceManager.GetString("NoFoedselsnummerInvalidCheckDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Foedselsnummer requires a valid six digit date of birth (DDMMYY) format in character positions 0-5 (zero-based).
        /// </summary>
        internal static string NoFoedselsnummerInvalidDateOfBirth {
            get {
                return ResourceManager.GetString("NoFoedselsnummerInvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Foedselsnummer must have length 11 (no separator character) or 12 (separator character).
        /// </summary>
        internal static string NoFoedselsnummerInvalidLength {
            get {
                return ResourceManager.GetString("NoFoedselsnummerInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Foedselsnummer separator character must not be a digit.
        /// </summary>
        internal static string NoFoedselsnummerInvalidSeparator {
            get {
                return ResourceManager.GetString("NoFoedselsnummerInvalidSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Personnummer may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string SePersonnummerEmpty {
            get {
                return ResourceManager.GetString("SePersonnummerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Personnummer contains a non-digit character where a digit was expected.
        /// </summary>
        internal static string SePersonnummerInvalidCharacter {
            get {
                return ResourceManager.GetString("SePersonnummerInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Personnummer must have a valid Luhn algorithm check digit in character position 10 (YYMMDD format) or character position 12 (YYYYMMDD format).
        /// </summary>
        internal static string SePersonnummerInvalidCheckDigit {
            get {
                return ResourceManager.GetString("SePersonnummerInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Personnummer requires valid six digit date of birth (YYMMDD) in character positions 0-5 (zero-based) or a valid eight digit date of birth (YYYYMMDD) in character positions 0-7 (zero-based).
        /// </summary>
        internal static string SePersonnummerInvalidDateOfBirth {
            get {
                return ResourceManager.GetString("SePersonnummerInvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Personnummer must have length 11 (YYMMDD format) or 13 (YYYYMMDD format).
        /// </summary>
        internal static string SePersonnummerInvalidLength {
            get {
                return ResourceManager.GetString("SePersonnummerInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Personnummer must have a valid separator character (either &apos;-&apos; or &apos;+&apos;) in character position 6 (zero-based, YYMMDD format) or character position 8 (zero-based, YYYYMMDD format).
        /// </summary>
        internal static string SePersonnummerInvalidSeparator {
            get {
                return ResourceManager.GetString("SePersonnummerInvalidSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Individual Taxpayer Identification Number may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string UsItinEmpty {
            get {
                return ResourceManager.GetString("UsItinEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Individual Taxpayer Identification Number area number segment (AAA-xx-xxxx) must not be 000-899.
        /// </summary>
        internal static string UsItinInvalidAreaNumber {
            get {
                return ResourceManager.GetString("UsItinInvalidAreaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Individual Taxpayer Identification Number must only contain digit characters (0-9) in non-separator character locations.
        /// </summary>
        internal static string UsItinInvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("UsItinInvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Individual Taxpayer Identification Number group number segment (xxx-GG-xxxx) must not be 00-49, 66-69, 89 or 93.
        /// </summary>
        internal static string UsItinInvalidGroupNumber {
            get {
                return ResourceManager.GetString("UsItinInvalidGroupNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Individual Taxpayer Identification Number must have length 9 (digits only) or 11 (9 digits with two separator characters).
        /// </summary>
        internal static string UsItinInvalidLength {
            get {
                return ResourceManager.GetString("UsItinInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Individual Taxpayer Identification Number with length 11 contains an unexpected character at a separator position.
        /// </summary>
        internal static string UsItinInvalidSeparatorEncountered {
            get {
                return ResourceManager.GetString("UsItinInvalidSeparatorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US National Provider Identifier may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string UsNpiEmpty {
            get {
                return ResourceManager.GetString("UsNpiEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US National Provider Identifier must only contain digit characters (0-9).
        /// </summary>
        internal static string UsNpiInvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("UsNpiInvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US National Provider Identifier contains an invalid check digit.
        /// </summary>
        internal static string UsNpiInvalidCheckDigit {
            get {
                return ResourceManager.GetString("UsNpiInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US National Provider Identifier must have length 10.
        /// </summary>
        internal static string UsNpiInvalidLength {
            get {
                return ResourceManager.GetString("UsNpiInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number may not have 9 consecutive identical digits.
        /// </summary>
        internal static string UsSsnAllIdenticalDigits {
            get {
                return ResourceManager.GetString("UsSsnAllIdenticalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string UsSsnEmpty {
            get {
                return ResourceManager.GetString("UsSsnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number area number segment (AAA-xx-xxxx) must not be 000, 666 or 900-999.
        /// </summary>
        internal static string UsSsnInvalidAreaNumber {
            get {
                return ResourceManager.GetString("UsSsnInvalidAreaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number must only contain digit characters (0-9) in non-separator character locations.
        /// </summary>
        internal static string UsSsnInvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("UsSsnInvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number group number segment (xxx-GG-xxxx) must not be 00.
        /// </summary>
        internal static string UsSsnInvalidGroupNumber {
            get {
                return ResourceManager.GetString("UsSsnInvalidGroupNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number must have length 9 (digits only) or 11 (9 digits with two separator characters).
        /// </summary>
        internal static string UsSsnInvalidLength {
            get {
                return ResourceManager.GetString("UsSsnInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number may not have sequence 123456789.
        /// </summary>
        internal static string UsSsnInvalidRun {
            get {
                return ResourceManager.GetString("UsSsnInvalidRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number with length 11 contains an unexpected character at a separator position.
        /// </summary>
        internal static string UsSsnInvalidSeparatorEncountered {
            get {
                return ResourceManager.GetString("UsSsnInvalidSeparatorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number serial number segment (xxx-xx-SSSS) must not be 0000.
        /// </summary>
        internal static string UsSsnInvalidSerialNumber {
            get {
                return ResourceManager.GetString("UsSsnInvalidSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not contain any validation errors.
        /// </summary>
        internal static string ValidationPassed {
            get {
                return ResourceManager.GetString("ValidationPassed", resourceCulture);
            }
        }
    }
}
