//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KfAccountNumbers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KfAccountNumbers.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string UsSsnEmpty {
            get {
                return ResourceManager.GetString("UsSsnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number area number segment (AAA-xx-xxxx) must not be 000, 666 or 900-999.
        /// </summary>
        internal static string UsSsnInvalidAreaNumber {
            get {
                return ResourceManager.GetString("UsSsnInvalidAreaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number contains an invalid character at location {0}; expected digit (0-9), found &apos;{1}&apos;.
        /// </summary>
        internal static string UsSsnInvalidCharacter {
            get {
                return ResourceManager.GetString("UsSsnInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number must have length 9 (digits only) or 11 (9 digits with two separator characters).
        /// </summary>
        internal static string UsSsnInvalidLength {
            get {
                return ResourceManager.GetString("UsSsnInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number contains an invalid separator character at location {0}; expected &apos;{1}&apos;, found &apos;{2}&apos;.
        /// </summary>
        internal static string UsSsnInvalidSeparator {
            get {
                return ResourceManager.GetString("UsSsnInvalidSeparator", resourceCulture);
            }
        }
    }
}
