//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KfAccountNumbers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KfAccountNumbers.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string CaSinEmpty {
            get {
                return ResourceManager.GetString("CaSinEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number must only contain digit characters (0-9) in non-separator character locations.
        /// </summary>
        internal static string CaSinInvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("CaSinInvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number contains an invalid check digit.
        /// </summary>
        internal static string CaSinInvalidCheckDigit {
            get {
                return ResourceManager.GetString("CaSinInvalidCheckDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number may not use a decimal digit (0-9) as a custom separator character.
        /// </summary>
        internal static string CaSinInvalidCustomSeparatorCharacter {
            get {
                return ResourceManager.GetString("CaSinInvalidCustomSeparatorCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number must have length 9 (digits only) or 11 (9 digits with two separator characters).
        /// </summary>
        internal static string CaSinInvalidLength {
            get {
                return ResourceManager.GetString("CaSinInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number may not have a leading digit (the province indicator) of zero (0) or eight (8).
        /// </summary>
        internal static string CaSinInvalidProvince {
            get {
                return ResourceManager.GetString("CaSinInvalidProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Social Insurance Number with length 11 contains an unexpected character at a separator position.
        /// </summary>
        internal static string CaSinInvalidSeparatorEncountered {
            get {
                return ResourceManager.GetString("CaSinInvalidSeparatorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateResult Failure error may not be null.
        /// </summary>
        internal static string CreateResultErrorNull {
            get {
                return ResourceManager.GetString("CreateResultErrorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateResult Success value may not be null.
        /// </summary>
        internal static string CreateResultValueNull {
            get {
                return ResourceManager.GetString("CreateResultValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string DescriptionEmpty {
            get {
                return ResourceManager.GetString("DescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String formatting mask may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string FormatMaskEmpty {
            get {
                return ResourceManager.GetString("FormatMaskEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to format with a mask may not be null.
        /// </summary>
        internal static string FormatStrNull {
            get {
                return ResourceManager.GetString("FormatStrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number may not have 9 consecutive identical digits.
        /// </summary>
        internal static string UsSsnAllIdenticalDigits {
            get {
                return ResourceManager.GetString("UsSsnAllIdenticalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number may not be null, empty or all whitespace characters.
        /// </summary>
        internal static string UsSsnEmpty {
            get {
                return ResourceManager.GetString("UsSsnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number area number segment (AAA-xx-xxxx) must not be 000, 666 or 900-999.
        /// </summary>
        internal static string UsSsnInvalidAreaNumber {
            get {
                return ResourceManager.GetString("UsSsnInvalidAreaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number must only contain digit characters (0-9) in non-separator character locations.
        /// </summary>
        internal static string UsSsnInvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("UsSsnInvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number may not use a decimal digit (0-9) as a custom separator character.
        /// </summary>
        internal static string UsSsnInvalidCustomSeparatorCharacter {
            get {
                return ResourceManager.GetString("UsSsnInvalidCustomSeparatorCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number group number segment (xxx-GG-xxxx) must not be 00.
        /// </summary>
        internal static string UsSsnInvalidGroupNumber {
            get {
                return ResourceManager.GetString("UsSsnInvalidGroupNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number must have length 9 (digits only) or 11 (9 digits with two separator characters).
        /// </summary>
        internal static string UsSsnInvalidLength {
            get {
                return ResourceManager.GetString("UsSsnInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null UsSocialSecurityNumber can not be converted to String.
        /// </summary>
        internal static string UsSsnInvalidNullConversionToString {
            get {
                return ResourceManager.GetString("UsSsnInvalidNullConversionToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number may not have sequence 123456789.
        /// </summary>
        internal static string UsSsnInvalidRun {
            get {
                return ResourceManager.GetString("UsSsnInvalidRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number with length 11 contains an unexpected character at a separator position.
        /// </summary>
        internal static string UsSsnInvalidSeparatorEncountered {
            get {
                return ResourceManager.GetString("UsSsnInvalidSeparatorEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Social Security Number serial number segment (xxx-xx-SSSS) must not be 0000.
        /// </summary>
        internal static string UsSsnInvalidSerialNumber {
            get {
                return ResourceManager.GetString("UsSsnInvalidSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not contain any validation errors.
        /// </summary>
        internal static string ValidationPassed {
            get {
                return ResourceManager.GetString("ValidationPassed", resourceCulture);
            }
        }
    }
}
