// Ignore Spelling: Deserialize Deserialization Foedselsnummer Json Kf Nummer

#pragma warning disable IDE0008 // Use explicit type
#pragma warning disable IDE0058 // Expression value is never used
#pragma warning disable CA2211 // Non-constant fields should not be visible

using LocalCreateResult = KfAccountNumbers.Results.CreateResult<
   KfAccountNumbers.Governmental.Europe.NoFoedselsnummer,
   KfAccountNumbers.Governmental.Europe.NoFoedselsnummer.ValidationError>;
using LocalValidationError = KfAccountNumbers.Governmental.Europe.NoFoedselsnummer.ValidationError;
using LocalValidationException = KfAccountNumbers.UKfValidationException<
   KfAccountNumbers.Governmental.Europe.NoFoedselsnummer.ValidationError>;
using LocalValidationResult = KfAccountNumbers.Governmental.Europe.NoFoedselsnummer.ValidationResult;

namespace KfAccountNumbers.Tests.Unit.Governmental.Europe;

public class NoFoedselsnummerTests
{
   private const String ValidUnformattedFoedselsnummer = "13029597140";          // Generated by https://norske-testdata.no/fnr/
   private const String AltValidUnformattedFoedselsnummer = "20055029572";
   private const String ValidFormattedFoedselsnummer = "130295 97140";
   private const String AltValidFormattedFoedselsnummer = "200550-29572";

   private const String ValidUnformattedDNummer = "53029597134";                 // Above values adjusted for D-nummer
   private const String AltValidUnformattedDNummer = "60055029566";
   private const String ValidFormattedDNummer = "530295 97134";
   private const String AltValidFormattedDNummer = "600550-29566";

   private static String GetRawFoedselsnummer(String foedselsnummer)
      => foedselsnummer.Length == 11
         ? foedselsnummer
         : foedselsnummer[..6] + foedselsnummer[7..];

   private static String GetFoedselsnummerWithValidCheckDigits(
      String dateOfBirth = "130295",
      String separator = "",
      String individualNumber = "971")
   {
      var d1 = dateOfBirth[0] - Chars.DigitZero;
      var d2 = dateOfBirth[1] - Chars.DigitZero;
      var d3 = dateOfBirth[2] - Chars.DigitZero;
      var d4 = dateOfBirth[3] - Chars.DigitZero;
      var d5 = dateOfBirth[4] - Chars.DigitZero;
      var d6 = dateOfBirth[5] - Chars.DigitZero;
      var i1 = individualNumber[0] - Chars.DigitZero;
      var i2 = individualNumber[1] - Chars.DigitZero;
      var i3 = individualNumber[2] - Chars.DigitZero;

      var sum1 = (3 * d1) + (7 * d2) + (6 * d3) + (1 * d4) + (8 * d5) + (9 * d6) + (4 * i1) + (5 * i2) + (2 * i3);
      var c1 = (11 - (sum1 % 11)) % 11;
      if (c1 == 10)
      {
         return String.Empty;
      }

      var sum2 = (5 * d1) + (4 * d2) + (3 * d3) + (2 * d4) + (7 * d5) + (6 * d6) + (5 * i1) + (4 * i2) + (3 * i3) + (2 * c1);
      var c2 = (11 - (sum2 % 11)) % 11;
      return c2 == 10 ? String.Empty : $"{dateOfBirth}{separator}{individualNumber}{c1}{c2}";
   }

   [Fact]
   public void GetTestValue()
   {
      var dateOfBirth = "701005";
      var separator = " ";
      var individualNumber = "678";

      var value = GetFoedselsnummerWithValidCheckDigits(dateOfBirth, separator, individualNumber);
      var x = value;
   }

   public static TheoryData<String> ValidFoedselsnummerValues =>
   [
      ValidUnformattedFoedselsnummer,
      AltValidUnformattedFoedselsnummer,
      ValidFormattedFoedselsnummer,
      AltValidFormattedFoedselsnummer,
   ];

   public static TheoryData<String> ValidDNummerValues =>
   [
      ValidUnformattedDNummer,
      AltValidUnformattedDNummer,
      ValidFormattedDNummer,
      AltValidFormattedDNummer,
   ];

   public static TheoryData<String> ValidSeparators =>
   [
      " ",
      "-",
      "A",
      "z",
      "!",
   ];

   public static TheoryData<String, String> ValidDateOfBirthValues = new()
   {
      // See class documentation on how the individual number and two digit year
      // are used to derive the four digit year. Note also that it is possible for
      // certain combinations to be invalid because of the modulus 11 check digit. In
      // those cases, the rows are duplicated and the day is adjusted in one and the
      // individual number is adjusted in the other

      // Minimum valid date = Jan 1, 1854
      // Maximum valid date = Dec 31, 2039

      // Rule 1 - individual number >= 500 and <= 749 and year >= 54 - century = 1800's
      { "010154", "500" },       // minimum 6 digit date and minimum individual number
      { "010154", "749" },       // minimum 6 digit date and maximum individual number
      { "311299", "500" },       // maximum 6 digit date and minimum individual number
      { "301299", "749" },       // maximum 6 digit date and maximum individual number (311299 749 adjusted because of check digits)
      { "311299", "748" },       // maximum 6 digit date and maximum individual number  "

      // Rule 2 - individual number < 500, year not considered - century = 1900's
      { "020100", "000" },       // minimum 6 digit date and minimum individual number (010100 000 adjusted because of check digits)
      { "010100", "001" },       // minimum 6 digit date and minimum individual number  "
      { "010100", "499" },       // minimum 6 digit date and maximum individual number
      { "301299", "000" },       // maximum 6 digit date and minimum individual number (311299 000 adjusted because of check digits)
      { "311299", "001" },       // maximum 6 digit date and minimum individual number  "
      { "311299", "499" },       // maximum 6 digit date and maximum individual number

      // Rule 3 - individual number >= 900 and year >= 40 - century = 1900's
      { "010140", "900" },       // minimum 6 digit date and minimum individual number
      { "010140", "999" },       // minimum 6 digit date and maximum individual number
      { "311299", "900" },       // maximum 6 digit date and minimum individual number
      { "301299", "999" },       // maximum 6 digit date and maximum individual number (311299 999 adjusted because of check digits)
      { "311299", "998" },       // maximum 6 digit date and maximum individual number  "

      // Rule 4 - individual number >= 500 and year <= 39 - century - 2000's
      { "010100", "500" },       // minimum 6 digit date and minimum individual number
      { "010100", "999" },       // minimum 6 digit date and maximum individual number
      { "311239", "500" },       // maximum 6 digit date and minimum individual number
      { "311239", "999" },       // maximum 6 digit date and maximum individual number

      // Month maximum days
      { "310104", "501" },       // maximum days for January, any year
      { "280201", "234" },       // maximum days for February, non-leap year
      { "290204", "234" },       // maximum days for February, leap year
      { "290200", "500" },       // maximum days for February, leap year (2000 is leap-year)
      { "310304", "501" },       // maximum days for March, any year
      { "300404", "499" },       // maximum days for April, any year
      { "310504", "501" },       // maximum days for May, any year
      { "300604", "500" },       // maximum days for June, any year
      { "310704", "501" },       // maximum days for July, any year
      { "310804", "501" },       // maximum days for August, any year
      { "300904", "500" },       // maximum days for September, any year
      { "311004", "501" },       // maximum days for October, any year
      { "301104", "499" },       // maximum days for November, any year
      { "311204", "500" },       // maximum days for December, any year

      // Repeat for D-nummer
      // Rule 1 - individual number >= 500 and <= 749 and year >= 54 - century = 1800's
      { "410154", "500" },       // minimum 6 digit date and minimum individual number
      { "410154", "749" },       // minimum 6 digit date and maximum individual number
      { "701299", "500" },       // maximum 6 digit date and minimum individual number (711299 500 adjusted because of check digits)
      { "711299", "501" },       // maximum 6 digit date and minimum individual number  "
      { "711299", "749" },       // maximum 6 digit date and maximum individual number

      // Rule 2 - individual number < 500, year not considered - century = 1900's
      { "410100", "000" },       // minimum 6 digit date and minimum individual number
      { "410100", "499" },       // minimum 6 digit date and maximum individual number
      { "711299", "000" },       // maximum 6 digit date and minimum individual number
      { "711299", "499" },       // maximum 6 digit date and maximum individual number

      // Rule 3 - individual number >= 900 and year >= 40 - century = 1900's
      { "410140", "900" },       // minimum 6 digit date and minimum individual number
      { "410140", "999" },       // minimum 6 digit date and maximum individual number
      { "711299", "900" },       // maximum 6 digit date and minimum individual number
      { "711299", "999" },       // maximum 6 digit date and maximum individual number

      // Rule 4 - individual number >= 500 and year <= 39 - century - 2000's
      { "410100", "500" },       // minimum 6 digit date and minimum individual number
      { "410100", "999" },       // minimum 6 digit date and maximum individual number
      { "711239", "500" },       // maximum 6 digit date and minimum individual number
      { "711239", "999" },       // maximum 6 digit date and maximum individual number

      // Month maximum days
      { "710104", "501" },       // maximum days for January, any year
      { "680201", "234" },       // maximum days for February, non-leap year
      { "690204", "234" },       // maximum days for February, leap year
      { "690200", "500" },       // maximum days for February, leap year (2000 is leap-year)
      { "710304", "500" },       // maximum days for March, any year
      { "700404", "499" },       // maximum days for April, any year
      { "710504", "501" },       // maximum days for May, any year
      { "700604", "500" },       // maximum days for June, any year
      { "710704", "501" },       // maximum days for July, any year
      { "710804", "501" },       // maximum days for August, any year
      { "700904", "500" },       // maximum days for September, any year
      { "711004", "501" },       // maximum days for October, any year
      { "701104", "499" },       // maximum days for November, any year
      { "711204", "500" },       // maximum days for December, any year
   };

   public static TheoryData<String> InvalidLengthValues =>
   [
      "1006127070",        // Length 10
      "100612-707079",     // Length 14
      new String('1', 100) // Very long string
   ];

   // Values that will report an invalid character encountered
   public static TheoryData<String, Int32> InvalidCharacterValues = new()
   {
      // Unformatted values
      { ".0061270707", 0 },         // Non-digit character '.'
      { "1 061270707", 1 },         // Non-digit character ' '
      { "10A61270707", 2 },         // Non-digit character 'A'
      { "100Z1270707", 3 },         // Non-digit character 'Z'
      { "1006^270707", 4 },         // Non-digit character '^'
      { "10061a70707", 5 },         // Non-digit character 'a'
      { "100612z0707", 6 },         // Non-digit character 'z'
      { "1006127~707", 7 },         // Non-digit character '~'
      { "10061270\u215307", 8 },    // Non-digit character Unicode fraction 1/3
      { "100612707\u00D67", 9 },    // Invalid character unicode O with umlaut
      { "1006127070\u0BE6", 10 },   // Invalid character unicode Tamil digit 0

      // Formatted values
      { ".00612 70707", 0 },        // Non-digit character '.'
      { "1 0612 70707", 1 },        // Non-digit character ' '
      { "10A612 70707", 2 },        // Non-digit character 'A'
      { "100Z12 70707", 3 },        // Non-digit character 'Z'
      { "1006^2 70707", 4 },        // Non-digit character '^'
      { "10061a 70707", 5 },        // Non-digit character 'a'
      { "100612 z0707", 7 },        // Non-digit character 'z'
      { "100612-7~707", 8 },        // Non-digit character '~'
      { "100612-70\u215307", 9 },   // Non-digit character Unicode fraction 1/3
      { "100612-707\u00D67", 10 },  // Invalid character unicode O with umlaut
      { "100612-7070\u0BE6", 11 },  // Invalid character unicode Tamil digit 0
   };

   public static TheoryData<String> InvalidCheckDigitValues =>
   [
      // Unformatted values
      "13039597140",          // 13029597140 with single digit transcription error 2 -> 3
      "20055025972",          // 20055029572 with two digit transposition error 95 -> 59
      "21072551149",          // 21072441149 with two digit twin error 44 -> 55
      "16072996853",          // 16079926853 with jump transposition 992 -> 299
      "13072101223",          // 13072101213 with invalid first check digit 1 -> 2
      "11085149989",          // 11085149980 with invalid second check digit 0 -> 9

      // Formatted values
      "130395 97140",         // 130295 97140 with single digit transcription error 2 -> 3
      "200550 25972",         // 200550 29572 with two digit transposition error 95 -> 59
      "210725 51149",         // 210724 41149 with two digit twin error 44 -> 55
      "160729 96853",         // 160799 26853 with jump transposition 992 -> 299
      "130721-01223",         // 130721-01213 with invalid first check digit 1 -> 2
      "110851-49989",         // 110851-49980 with invalid second check digit 0 -> 9
   ];

   public static TheoryData<String> InvalidSeparators =>
   [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
   ];

   public static TheoryData<String, String> InvalidDateOfBirthValues = new()
   {
      // See ValidDateOfBirthValues above for more info on design of date of birth/individual number pairs.

      // Rule 1 - individual number >= 500 and <= 749 and year >= 54 - century = 1800's
      { "010153", "500" },       // minimum 6 digit date and minimum individual number - less than minimum valid date
      { "010153", "749" },       // minimum 6 digit date and maximum individual number - "

      // Rule 2 - individual number < 500, year not considered - century = 1900's
      // No valid 6 digit dates fall outside valid range

      // Rule 3 - individual number >= 900 and year >= 40 - century = 1900's
      // No valid 6 digit dates fall outside valid range

      // Rule 4 - individual number >= 500 and year <= 39 - century - 2000's
      { "010140", "500" },       // minimum 6 digit date and minimum individual number - greater than maximum valid date
      { "010140", "899" },       // minimum 6 digit date and maximum individual number - "

      // Invalid months
      { "010004", "500" },       // month = 0
      { "011304", "500" },       // month = 13

      // Invalid days
      { "000104", "500" },       // days = 0
      { "320104", "500" },       // Invalid day of month for January, any year
      { "290201", "502" },       // Invalid day of for February, non-leap year
      { "300204", "501" },       // Invalid day of for February, leap year
      { "300200", "500" },       // Invalid day of for February, leap year (2000 is leap-year)
      { "320304", "500" },       // Invalid day of for March, any year
      { "310404", "502" },       // Invalid day of for April, any year
      { "320504", "500" },       // Invalid day of for May, any year
      { "310604", "501" },       // Invalid day of for June, any year
      { "320704", "500" },       // Invalid day of for July, any year
      { "320804", "500" },       // Invalid day of for August, any year
      { "310904", "501" },       // Invalid day of for September, any year
      { "321004", "500" },       // Invalid day of for October, any year
      { "311104", "500" },       // Invalid day of for November, any year
      { "321204", "500" },       // Invalid day of for December, any year

      // Repeat for D-nummer
      // Rule 1 - individual number >= 500 and <= 749 and year >= 54 - century = 1800's
      { "410153", "500" },       // minimum 6 digit date and minimum individual number - less than minimum valid date
      { "410153", "749" },       // minimum 6 digit date and maximum individual number - "

      // Rule 2 - individual number < 500, year not considered - century = 1900's
      // No valid 6 digit dates fall outside valid range

      // Rule 3 - individual number >= 900 and year >= 40 - century = 1900's
      // No valid 6 digit dates fall outside valid range

      // Rule 4 - individual number >= 500 and year <= 39 - century - 2000's
      { "410140", "501" },       // minimum 6 digit date and minimum individual number - greater than maximum valid date
      { "410140", "899" },       // minimum 6 digit date and maximum individual number - "

      // Invalid months
      { "410004", "500" },       // Invalid month = 0
      { "411304", "500" },       // Invalid month = 13

      // Invalid days
      { "400104", "500" },       // Invalid day = 0
      { "720104", "500" },       // Invalid day of month for January, any year
      { "690201", "500" },       // Invalid day of for February, non-leap year
      { "700204", "500" },       // Invalid day of for February, leap year
      { "700200", "500" },       // Invalid day of for February, leap year (2000 is leap-year)
      { "720304", "500" },       // Invalid day of for March, any year
      { "710404", "500" },       // Invalid day of for April, any year
      { "720504", "500" },       // Invalid day of for May, any year
      { "710604", "500" },       // Invalid day of for June, any year
      { "720704", "500" },       // Invalid day of for July, any year
      { "720804", "500" },       // Invalid day of for August, any year
      { "710904", "500" },       // Invalid day of for September, any year
      { "721004", "500" },       // Invalid day of for October, any year
      { "711104", "500" },       // Invalid day of for November, any year
      { "721204", "500" },       // Invalid day of for December, any year

      // H nummer (40 added to month) not currently supported
      { "014154", "500" },

      // FH nummer (starts with 8 or 9) not currently supported
      { "810100", "501" },
      { "910100", "501" },
   };

   private static InvalidLength GetInvalidLengthResult(String value)
      => new(
         Messages.NoFoedselsnummerInvalidLength,
         value.Length,
         NoFoedselsnummer.GetValidLengthDefinitions());

   private static InvalidCharacter GetInvalidCharacterResult(
      String value,
      Int32 position)
      => new(
         Messages.NoFoedselsnummerInvalidCharacter,
         value[position],
         position);

   private static InvalidChecksum GetInvalidChecksumResult()
      => new(
         Messages.NoFoedselsnummerInvalidCheckDigits,
         NoFoedselsnummer.CheckDigitAlgorithmName);

   private static InvalidSeparator GetInvalidSeparatorResult(String value)
      => new(Messages.NoFoedselsnummerInvalidSeparator, value[6], 6);

   private static InvalidDateOfBirth GetInvalidDateOfBirthResult(String value)
      => new(Messages.NoFoedselsnummerInvalidDateOfBirth, value[..6], DateFormatName.DDMMYY);

   #region Constants Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_CheckDigitAlgorithmName_ShouldHaveExpectedValue()
      => NoFoedselsnummer.CheckDigitAlgorithmName.Should().Be("Weighted Modulus 11");

   [Fact]
   public void NoFoedselsnummer_MinimumValidYearOfBirth_ShouldHaveExpectedValue()
      => NoFoedselsnummer.MinimumValidYearOfBirth.Should().Be(1854);

   [Fact]
   public void NoFoedselsnummer_MaximumValidYearOfBirth_ShouldHaveExpectedValue()
      => NoFoedselsnummer.MaximumValidYearOfBirth.Should().Be(2039);

   [Fact]
   public void NoFoedselsnummer_DNummerDayOffset_ShouldHaveExpectedValue()
      => NoFoedselsnummer.DNummerDayOffset.Should().Be(40);

   #endregion

   #region Constructor Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_Constructor_ShouldCreateInstance_WhenValueIsValid(String value)
   {
      // Arrange.
      var expected = GetRawFoedselsnummer(value);

      // Act.
      var sut = new NoFoedselsnummer(value);

      // Assert.
      sut.Should().NotBeNull();
      sut.Value.Should().Be(expected);
   }

   [Theory]
   [MemberData(nameof(ValidSeparators))]
   public void NoFoedselsnummer_Constructor_ShouldCreateInstance_WhenValueHasValidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      var expected = GetRawFoedselsnummer(value);

      // Act.
      var sut = new NoFoedselsnummer(value);

      // Assert.
      sut.Should().NotBeNull();
      sut.Value.Should().Be(expected);
   }

   [Theory]
   [MemberData(nameof(ValidDateOfBirthValues))]
   public void NoFoedselsnummer_Constructor_ShouldCreateInstance_WhenValueHasValidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var expected = GetRawFoedselsnummer(value);

      // Act.
      var sut = new NoFoedselsnummer(value);

      // Assert.
      sut.Should().NotBeNull();
      sut.Value.Should().Be(expected);
   }

   [Theory]
   [ClassData(typeof(StringNullEmptyWhitespaceValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueIsNullOrEmpty(String value)
   {
      // Arrange.
      LocalValidationError expected = default(EmptyValue);

      // Act/assert.
      FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidLengthValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasInvalidLength(String value)
   {
      // Arrange.
      LocalValidationError expected = GetInvalidLengthResult(value);

      // Act/assert.
      FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected, options => options        // Options necessary because FluentAssertions gets lost comparing the ValidLengthDefinition array in InvalidLength type
            .ComparingByMembers<LocalValidationError>()
            .ComparingByMembers<ValidLengthDefinition>()
            .WithoutStrictOrdering());
   }

   [Theory]
   [MemberData(nameof(InvalidCharacterValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasNonDigitCharacter(
      String value,
      Int32 position)
   {
      // Arrange.
      LocalValidationError expected = GetInvalidCharacterResult(value, position);

      // Act/assert.
      FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidCheckDigitValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasInvalidCheckDigits(String value)
   {
      // Arrange.
      LocalValidationError expected = GetInvalidChecksumResult();

      // Act/assert.
      FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidSeparators))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasInvalidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      LocalValidationError expected = GetInvalidSeparatorResult(value);

      // Act/assert.
      FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidDateOfBirthValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasInvalidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      LocalValidationError expected = GetInvalidDateOfBirthResult(value);

      // Act/assert.
      FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   #endregion

   #region DateOfBirth Property Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   // See ValidDateOfBirthValues property for rules associated with the individual numbers
   [InlineData("010154", "500", "18540101")]       // Rule 1, January 1, 1854
   [InlineData("311299", "748", "18991231")]       // Rule 1, December 31, 1899
   [InlineData("010100", "001", "19000101")]       // Rule 2, January 1, 1900
   [InlineData("311299", "499", "19991231")]       // Rule 2, December 31, 1999
   [InlineData("010140", "900", "19400101")]       // Rule 3, January 1, 1940
   [InlineData("311299", "998", "19991231")]       // Rule 3, December 31, 1999
   [InlineData("010100", "500", "20000101")]       // Rule 4, January 1, 2000
   [InlineData("311239", "999", "20391231")]       // Rule 4, December 31, 2039
   [InlineData("290296", "501", "18960229")]       // February 29, 1896 - leap year
   [InlineData("280200", "235", "19000228")]       // February 28, 1900 - non leap year
   [InlineData("290248", "318", "19480229")]       // February 29, 1948 - leap year
   [InlineData("290200", "601", "20000229")]       // February 29, 2000 - leap year

   // D-nummer values
   [InlineData("410154", "500", "18540101")]       // Rule 1, January 1, 1854
   [InlineData("711299", "748", "18991231")]       // Rule 1, December 31, 1899
   [InlineData("410100", "001", "19000101")]       // Rule 2, January 1, 1900
   [InlineData("711299", "499", "19991231")]       // Rule 2, December 31, 1999
   [InlineData("410140", "900", "19400101")]       // Rule 3, January 1, 1940
   [InlineData("711299", "998", "19991231")]       // Rule 3, December 31, 1999
   [InlineData("410100", "500", "20000101")]       // Rule 4, January 1, 2000
   [InlineData("711239", "999", "20391231")]       // Rule 4, December 31, 2039
   [InlineData("690296", "501", "18960229")]       // February 29, 1896 - leap year
   [InlineData("680200", "235", "19000228")]       // February 28, 1900 - non leap year
   [InlineData("690248", "318", "19480229")]       // February 29, 1948 - leap year
   [InlineData("690200", "601", "20000229")]       // February 29, 2000 - leap year
   public void NoFoedselsnummer_DateOfBirth_ShouldReturnExpectedValue(
      String dateOfBirth,
      String individualNumber,
      String expectedDateOfBirth)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var sut = new NoFoedselsnummer(value);
      var expected = DateOnly.ParseExact(
         expectedDateOfBirth,
         "yyyyMMdd",
         CultureInfo.InvariantCulture);

      // Act/assert.
      sut.DateOfBirth.Should().Be(expected);
   }

   #endregion

   #region Gender Property Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [InlineData("541", "")]
   [InlineData("543", "")]
   [InlineData("545", "")]
   [InlineData("547", "")]
   [InlineData("549", "")]
   [InlineData("541", " ")]
   [InlineData("543", " ")]
   [InlineData("545", " ")]
   [InlineData("547", " ")]
   [InlineData("549", " ")]
   public void NoFoedselsnummer_Gender_ShouldReturnMale_ForValuesWithOddGenderIndicator(
      String individualNumber,
      String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         individualNumber: individualNumber,
         separator: separator);
      var sut = new NoFoedselsnummer(value);
      Gender.BinaryGender expected = default(Gender.Male);

      // Act/assert.
      sut.Gender.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [InlineData("540", "")]
   [InlineData("542", "")]
   [InlineData("544", "")]
   [InlineData("546", "")]
   [InlineData("648", "")]     // 5 changed to 6 because of modulus 11 check digits
   [InlineData("540", " ")]
   [InlineData("542", " ")]
   [InlineData("544", " ")]
   [InlineData("546", " ")]
   [InlineData("648", " ")]    // 5 changed to 6 because of modulus 11 check digits
   public void NoFoedselsnummer_Gender_ShouldReturnFemale_ForValuesWithEvenGenderIndicator(
      String individualNumber,
      String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         individualNumber: individualNumber,
         separator: separator);
      var sut = new NoFoedselsnummer(value);
      Gender.BinaryGender expected = default(Gender.Female);

      // Act/assert.
      sut.Gender.Should().BeEquivalentTo(expected);
   }

   #endregion

   #region IdentifierType Property Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [InlineData("010154", "500")]
   [InlineData("311239", "999")]
   public void NoFoedselsnummer_IdentifierType_ShouldReturnExpectedValue_WhenValueIsFoedselsnummer(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var sut = new NoFoedselsnummer(value);
      NoFoedselsnummer.IdentifierCategory expected = default(NoIdentifierType.Foedselsnummer);

      // Act/assert.
      sut.IdentifierType.Should().Be(expected);
   }

   [Theory]
   [InlineData("410154", "500")]
   [InlineData("711239", "999")]
   public void NoFoedselsnummer_IdentifierType_ShouldReturnExpectedValue_WhenValueIsDNummer(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var sut = new NoFoedselsnummer(value);
      NoFoedselsnummer.IdentifierCategory expected = default(NoIdentifierType.DNummer);

      // Act/assert.
      sut.IdentifierType.Should().Be(expected);
   }

   #endregion

   #region Value Property Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [InlineData(ValidUnformattedFoedselsnummer, ValidUnformattedFoedselsnummer)]
   [InlineData(ValidFormattedFoedselsnummer, ValidUnformattedFoedselsnummer)]
   [InlineData(ValidUnformattedDNummer, ValidUnformattedDNummer)]
   [InlineData(ValidFormattedDNummer, ValidUnformattedDNummer)]
   public void NoFoedselsnummer_Value_ShouldReturnValidatedFoedselsnummer(
      String value,
      String expected)
   {
      // Arrange.
      var sut = new NoFoedselsnummer(value);

      // Act/assert.
      sut.Value.Should().Be(expected);
   }

   #endregion

   #region Conversion Operator Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_ImplicitToStringConversion_ShouldReturnExpectedValue_WhenValueIsNotNull()
   {
      // Arrange.
      var value = ValidUnformattedFoedselsnummer;
      var sut = new NoFoedselsnummer(value);

      // Act.
      String str = sut;

      // Assert.
      str.Should().Be(sut.Value);
   }

   [Fact]
   public void NoFoedselsnummer_CastToString_ShouldReturnExpectedValue_WhenValueIsNotNull()
   {
      // Arrange.
      var value = ValidFormattedDNummer;
      var sut = new NoFoedselsnummer(value);

      // Act.
      var str = (String)sut;

      // Assert.
      str.Should().NotBeNullOrEmpty();
      str.Should().Be(sut.Value);
   }

   [Fact]
   public void NoFoedselsnummer_ImplicitToStringConversion_ShouldReturnEmptyString_WhenValueIsNull()
   {
      // Arrange.
      NoFoedselsnummer sut = null!;

      // Act.
      String str = sut;

      // Assert.
      str.Should().NotBeNull();
      str.Should().BeEmpty();
   }

   [Fact]
   public void NoFoedselsnummer_CastToString_ShouldReturnEmptyString_WhenValueIsNull()
   {
      // Arrange.
      NoFoedselsnummer sut = null!;

      // Act.
      var str = (String)sut;

      // Assert.
      str.Should().NotBeNull();
      str.Should().BeEmpty();
   }

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldCreateInstance_WhenValueIsValid(String value)
   {
      // Arrange.
      var expected = new NoFoedselsnummer(value);

      // Act.
      var sut = (NoFoedselsnummer)value;

      // Assert.
      sut.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(ValidSeparators))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldCreateInstance_WhenValueHasValidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      var expected = new NoFoedselsnummer(value);

      // Act.
      var sut = (NoFoedselsnummer)value;

      // Assert.
      sut.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(ValidDateOfBirthValues))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldCreateInstance_WhenValueHasValidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var expected = new NoFoedselsnummer(value);

      // Act.
      var sut = (NoFoedselsnummer)value;

      // Assert.
      sut.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [ClassData(typeof(StringNullEmptyWhitespaceValues))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldThrowKfValidationException_WhenValueIsNullOrEmpty(String value)
   {
      // Arrange.
      LocalValidationError expected = default(EmptyValue);

      // Act/assert.
      FluentActions
         .Invoking(() => _ = (NoFoedselsnummer)value)
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidLengthValues))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldThrowKfValidationException_WhenValueHasInvalidLength(String value)
   {
      // Arrange.
      LocalValidationError expected = GetInvalidLengthResult(value);

      // Act/assert.
      FluentActions
         .Invoking(() => _ = (NoFoedselsnummer)value)
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected, options => options        // Options necessary because FluentAssertions gets lost comparing the ValidLengthDefinition array in InvalidLength type
            .ComparingByMembers<LocalValidationError>()
            .ComparingByMembers<ValidLengthDefinition>()
            .WithoutStrictOrdering());
   }

   [Theory]
   [MemberData(nameof(InvalidCharacterValues))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldThrowKfValidationException_WhenValueHasNonDigitCharacter(
      String value,
      Int32 position)
   {
      // Arrange.
      LocalValidationError expected = GetInvalidCharacterResult(value, position);

      // Act/assert.
      FluentActions
         .Invoking(() => _ = (NoFoedselsnummer)value)
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidCheckDigitValues))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldThrowKfValidationException_WhenValueHasInvalidCheckDigits(String value)
   {
      // Arrange.
      LocalValidationError expected = GetInvalidChecksumResult();

      // Act/assert.
      FluentActions
         .Invoking(() => _ = (NoFoedselsnummer)value)
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidSeparators))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldThrowKfValidationException_WhenValueHasInvalidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      LocalValidationError expected = GetInvalidSeparatorResult(value);

      // Act/assert.
      FluentActions
         .Invoking(() => _ = (NoFoedselsnummer)value)
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidDateOfBirthValues))]
   public void NoFoedselsnummer_ExplicitCastToNoFoedselsnummer_ShouldThrowKfValidationException_WhenValueHasInvalidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      LocalValidationError expected = GetInvalidDateOfBirthResult(value);

      // Act/assert.
      FluentActions
         .Invoking(() => _ = (NoFoedselsnummer)value)
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   #endregion

   #region Equality Operator Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_EqualityOperator_ShouldReturnTrue_WhenValuesAreEqual()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);

      // Act/assert.
      (sut1 == sut2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_EqualityOperator_ShouldReturnFalse_WhenValuesAreNotEqual()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(AltValidUnformattedFoedselsnummer);

      // Act/assert.
      (sut1 == sut2).Should().BeFalse();
   }

   [Fact]
   public void NoFoedselsnummer_EqualityOperator_ShouldReturnTrue_WhenValuesHaveDifferentLengths()
   {
      // Arrange. 11 and 12 character versions for same person should still be equal.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidFormattedFoedselsnummer);

      // Act/assert.
      (sut1 == sut2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_EqualityOperator_ShouldReturnTrue_WhenValuesDifferOnlyBySeparators()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidFormattedDNummer);
      var sut2 = new NoFoedselsnummer(ValidFormattedDNummer.Replace(' ', '.'));

      // Act/assert.
      (sut1 == sut2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_EqualityOperator_ShouldReturnTrue_WhenValuesDifferOnlyBySeparatorCase()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidFormattedDNummer.Replace(' ', 'A'));
      var sut2 = new NoFoedselsnummer(ValidFormattedDNummer.Replace(' ', 'a'));

      // Act/assert.
      (sut1 == sut2).Should().BeTrue();
   }

   #endregion

   #region Inequality Operator Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_InequalityOperator_ShouldReturnTrue_WhenValuesAreNotEqual()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(AltValidUnformattedFoedselsnummer);

      // Act/assert.
      (sut1 != sut2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_InequalityOperator_ShouldReturnFalse_WhenValuesHaveDifferentLengths()
   {
      // Arrange. 11 and 12 character versions for same person should still be equal.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidFormattedFoedselsnummer);

      // Act/assert.
      (sut1 != sut2).Should().BeFalse();
   }

   [Fact]
   public void NoFoedselsnummer_InequalityOperator_ShouldReturnFalse_WhenValuesAreEqual()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);

      // Act/assert.
      (sut1 != sut2).Should().BeFalse();
   }

   [Fact]
   public void NoFoedselsnummer_InequalityOperator_ShouldReturnFalse_WhenValuesDifferOnlyBySeparators()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidFormattedDNummer);
      var sut2 = new NoFoedselsnummer(ValidFormattedDNummer.Replace(' ', '.'));

      // Act/assert.
      (sut1 != sut2).Should().BeFalse();
   }

   [Fact]
   public void NoFoedselsnummer_InequalityOperator_ShouldReturnFalse_WhenValuesDifferOnlyBySeparatorCase()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidFormattedDNummer.Replace(' ', 'A'));
      var sut2 = new NoFoedselsnummer(ValidFormattedDNummer.Replace(' ', 'a'));

      // Act/assert.
      (sut1 != sut2).Should().BeFalse();
   }

   #endregion

   #region Create Method Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_Create_ShouldCreateInstance_WhenValueIsValid(String value)
   {
      // Arrange.
      LocalCreateResult expected = new NoFoedselsnummer(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(ValidSeparators))]
   public void NoFoedselsnummer_Create_ShouldCreateInstance_WhenValueHasValidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      LocalCreateResult expected = new NoFoedselsnummer(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(ValidDateOfBirthValues))]
   public void NoFoedselsnummer_Create_ShouldCreateInstance_WhenValueHasValidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      LocalCreateResult expected = new NoFoedselsnummer(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [ClassData(typeof(StringNullEmptyWhitespaceValues))]
   public void NoFoedselsnummer_Create_ShouldReturnEmptyValidationResult_WhenValueIsEmpty(String value)
   {
      // Arrange.
      LocalCreateResult expected = (LocalValidationError)default(EmptyValue);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidLengthValues))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidLengthValidationResult_WhenValueHasInvalidLength(String value)
   {
      // Arrange.
      LocalCreateResult expected = (LocalValidationError)GetInvalidLengthResult(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected, options => options                         // Options necessary because FluentAssertions gets lost comparing the ValidLengthDefinition array in InvalidLength type
         .ComparingByMembers<LocalCreateResult>()
         .ComparingByMembers<LocalValidationError>()
         .ComparingByMembers<ValidLengthDefinition>()
         .WithoutStrictOrdering());
   }

   [Theory]
   [MemberData(nameof(InvalidCharacterValues))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidCharacterValidationResult_WhenValueHasNonDigitCharacter(
      String value,
      Int32 position)
   {
      // Arrange.
      LocalCreateResult expected = (LocalValidationError)GetInvalidCharacterResult(value, position);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidCheckDigitValues))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidCheckDigitsValidationResult_WhenValueHasInvalidCheckDigits(String value)
   {
      // Arrange.
      LocalCreateResult expected = (LocalValidationError)GetInvalidChecksumResult();

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidSeparators))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidSeparatorValidationResult_WhenValueHasInvalidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      LocalCreateResult expected = (LocalValidationError)GetInvalidSeparatorResult(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidDateOfBirthValues))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidDateOfBirthValidationResult_WhenValueHasInvalidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      LocalCreateResult expected = (LocalValidationError)GetInvalidDateOfBirthResult(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   #endregion

   #region Equals Method Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_Equals_ShouldReturnTrue_WhenValuesAreEqual()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);

      // Act/assert.
      sut1.Equals(sut2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_Equals_ShouldReturnFalse_WhenValuesAreNotEqual()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(AltValidUnformattedFoedselsnummer);

      // Act/assert.
      sut1.Equals(sut2).Should().BeFalse();
   }

   [Fact]
   public void NoFoedselsnummer_Equals_ShouldReturnTrue_WhenValuesHaveDifferentLengths()
   {
      // Arrange. 11 and 12 character versions for same person should still be equal.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidFormattedFoedselsnummer);

      // Act/assert.
      sut1.Equals(sut2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_Equals_ShouldReturnTrue_WhenValuesDifferOnlyBySeparators()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidFormattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidFormattedFoedselsnummer.Replace(' ', '.'));

      // Act/assert.
      sut1.Equals(sut2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_Equals_ShouldReturnTrue_WhenValuesDifferOnlyBySeparatorCase()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidFormattedFoedselsnummer.Replace(' ', 'A'));
      var sut2 = new NoFoedselsnummer(ValidFormattedFoedselsnummer.Replace(' ', 'a'));

      // Act/assert.
      sut1.Equals(sut2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_Equals_ShouldReturnFalse_WhenComparedToDifferentType()
   {
      // Arrange.
      var sut = new NoFoedselsnummer(ValidFormattedFoedselsnummer);

      // Act/assert.
      sut.Equals(ValidFormattedFoedselsnummer).Should().BeFalse();
   }

   [Fact]
   public void NoFoedselsnummer_Equals_ShouldReturnFalse_WhenComparedWithNull()
   {
      // Arrange.
      var sut = new NoFoedselsnummer(ValidFormattedFoedselsnummer);

      // Act/assert.
      sut.Equals(null).Should().BeFalse();
   }

   #endregion

   #region Format Method Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_Format_ShouldReturnExpectedString_WhenDefaultMaskIsUsed()
   {
      // Arrange.
      var sut = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var expected = ValidFormattedFoedselsnummer;

      // Act.
      var str = sut.Format();

      // Assert.
      str.Should().Be(expected);
   }

   [Fact]
   public void NoFoedselsnummer_Format_ShouldReturnExpectedString_WhenCustomMaskIsUsed()
   {
      // Arrange.
      var sut = new NoFoedselsnummer(AltValidUnformattedFoedselsnummer);
      var mask = "______-_____";
      var expected = AltValidFormattedFoedselsnummer;

      // Act.
      var str = sut.Format(mask);

      // Assert.
      str.Should().Be(expected);
   }

   [Fact]
   public void NoFoedselsnummer_Format_ShouldThrowArgumentNullException_WhenMaskIsNull()
   {
      // Arrange.
      var sut = new NoFoedselsnummer(ValidUnformattedDNummer);
      String mask = null!;

      // Act/assert.
      FluentActions
         .Invoking(() => _ = sut.Format(mask))
         .Should()
         .ThrowExactly<ArgumentNullException>()
         .WithParameterName(nameof(mask))
         .WithMessage(Messages.FormatMaskEmpty + "*");
   }

   [Theory]
   [InlineData("")]
   [InlineData("\t")]
   public void NoFoedselsnummer_Format_ShouldThrowArgumentException_WhenMaskIsEmpty(String mask)
   {
      // Arrange.
      var sut = new NoFoedselsnummer(AltValidUnformattedDNummer);
      var expectedMessage = Messages.FormatMaskEmpty + "*";
      var act = () => _ = sut.Format(mask);

      // Act/assert.
      act.Should().ThrowExactly<ArgumentException>()
         .WithParameterName(nameof(mask))
         .WithMessage(expectedMessage);
   }

   #endregion

   #region GetHashCode Method Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_GetHashCode_ShouldBeConsistent_WhenValuesAreEqual()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);

      // Act.
      var hash1 = sut1.GetHashCode();
      var hash2 = sut2.GetHashCode();

      // Assert.
      hash1.Should().Be(hash2);
   }

   [Fact]
   public void NoFoedselsnummer_GetHashCode_ShouldReturnDifferentValues_WhenValuesAreDifferent()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedDNummer);
      var sut2 = new NoFoedselsnummer(AltValidUnformattedDNummer);

      // Act.
      var hash1 = sut1.GetHashCode();
      var hash2 = sut2.GetHashCode();

      // Assert.
      hash1.Should().NotBe(hash2);
   }

   [Fact]
   public void NoFoedselsnummer_GetHashCode_ShouldBeConsistent_WhenValuesHaveDifferentLengths()
   {
      // Arrange. 11 and 12 character versions for same person should still be equal.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidFormattedFoedselsnummer);

      // Act.
      var hash1 = sut1.GetHashCode();
      var hash2 = sut2.GetHashCode();

      // Assert.
      hash1.Should().Be(hash2);
   }

   [Fact]
   public void NoFoedselsnummer_GetHashCode_ShouldBeConsistent_WhenValuesDifferOnlyBySeparators()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidFormattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidFormattedFoedselsnummer.Replace(' ', '.'));

      // Act.
      var hash1 = sut1.GetHashCode();
      var hash2 = sut2.GetHashCode();

      // Assert.
      hash1.Should().Be(hash2);
   }

   [Fact]
   public void NoFoedselsnummer_GetHashCode_ShouldBeConsistent_WhenValuesDifferOnlyBySeparatorCase()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidFormattedFoedselsnummer.Replace(' ', 'A'));
      var sut2 = new NoFoedselsnummer(ValidFormattedFoedselsnummer.Replace(' ', 'a'));

      // Act.
      var hash1 = sut1.GetHashCode();
      var hash2 = sut2.GetHashCode();

      // Assert.
      hash1.Should().Be(hash2);
   }

   #endregion

   #region ReferenceEquals Method Tests
   // ==========================================================================
   // ==========================================================================

   // NoFoedselsnummer does not override Object.ReferenceEquals, so this test just
   // confirms that two different instances with the same value are not
   // considered reference equal.

   [Fact]
   public void NoFoedselsnummer_ObjectReferenceEquals_ShouldReturnFalse_WhenValuesAreEqualButInstancesAreDifferent()
   {
      // Arrange.
      var sut1 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);
      var sut2 = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);

      // Act/assert.
      (sut1 == sut2).Should().BeTrue();                         // Value equality should be true
      ReferenceEquals(sut1, sut2).Should().BeFalse();
   }

   #endregion

   #region ToString Method Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_ToString_ShouldReturnExpectedValue(String value)
   {
      // Arrange.
      var sut = new NoFoedselsnummer(value);
      var expected = GetRawFoedselsnummer(value);

      // Act/assert.
      sut.ToString().Should().Be(expected);
   }

   #endregion

   #region Validate Method Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnValidationPassed_WhenValueIsValid(String value)
   {
      // Arrange.
      LocalValidationResult expected = default(ValidValue);

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(ValidSeparators))]
   public void NoFoedselsnummer_Validate_ShouldReturnValidationPassed_WhenValueHasValidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      LocalValidationResult expected = default(ValidValue);

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(ValidDateOfBirthValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnValidationPassed_WhenValueHasValidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      LocalValidationResult expected = default(ValidValue);

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [ClassData(typeof(StringNullEmptyWhitespaceValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnEmpty_WhenValueIsNullOrEmpty(String value)
   {
      // Arrange.
      LocalValidationResult expected = default(EmptyValue);

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidLengthValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidLength_WhenValueHasInvalidLength(String value)
   {
      // Arrange.
      LocalValidationResult expected = GetInvalidLengthResult(value);

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected, options => options    // Options necessary because FluentAssertions gets lost comparing the ValidLengthDefinition array in InvalidLength type
         .ComparingByMembers<LocalValidationResult>()
         .ComparingByMembers<ValidLengthDefinition>()
         .WithoutStrictOrdering());
   }

   [Theory]
   [MemberData(nameof(InvalidCharacterValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidCharacter_WhenValueHasNonDigitCharacter(
      String value,
      Int32 position)
   {
      // Arrange.
      LocalValidationResult expected = GetInvalidCharacterResult(value, position);

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidCheckDigitValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidCheckDigits_WhenValueHasInvalidCheckDigits(String value)
   {
      // Arrange.
      LocalValidationResult expected = GetInvalidChecksumResult();

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidSeparators))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidSeparator_WhenValueHasInvalidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      LocalValidationResult expected = GetInvalidSeparatorResult(value);

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   [Theory]
   [MemberData(nameof(InvalidDateOfBirthValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidDateOfBirth_WhenValueHasInvalidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      LocalValidationResult expected = GetInvalidDateOfBirthResult(value);

      // Act.
      var result = NoFoedselsnummer.Validate(value);

      // Assert.
      result.Should().BeEquivalentTo(expected);
   }

   #endregion

   #region Json Serialization Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_JsonSerialization_ShouldRoundTripSuccessfully()
   {
      // Arrange.
      var sut = new NoFoedselsnummer(ValidUnformattedFoedselsnummer);

      // Act.
      var json = JsonSerializer.Serialize(sut);
      var result = JsonSerializer.Deserialize<NoFoedselsnummer>(json);

      // Assert.
      result.Should().NotBeNull();
      result.Should().BeEquivalentTo(sut);
   }

   [Fact]
   public void NoFoedselsnummer_JsonSerialization_ShouldSerializeAsStringInsteadOfObject()
   {
      // Arrange.
      var sut = new NoFoedselsnummer(ValidFormattedDNummer);
      var expected = sut.Value;

      // Act.
      var json = JsonSerializer.Serialize(sut);

      // Assert.
      json.Should().Be($"\"{expected}\"");  // Simple string, not object
   }

   public class Foo
   {
      public NoFoedselsnummer Foedselsnummer { get; set; } = null!;
   }

   [Fact]
   public void NoFoedselsnummer_JsonSerialization_ShouldDeserializeComplexObject()
   {
      // Arrange.
      var foo = new Foo { Foedselsnummer = new NoFoedselsnummer(ValidFormattedFoedselsnummer) };
      var json = JsonSerializer.Serialize(foo);

      // Act.
      var result = JsonSerializer.Deserialize<Foo>(json);

      // Assert.
      result.Should().NotBeNull();
      result.Should().BeEquivalentTo(foo);
   }

   [Fact]
   public void NoFoedselsnummer_JsonSerialization_ShouldSerializeNullGracefully()
   {
      // Arrange.
      var expected = /*lang=json,strict*/ "{\"Foedselsnummer\":null}";
      var foo = new Foo();

      // Act.
      var json = JsonSerializer.Serialize(foo);

      // Assert.
      json.Should().Be(expected);
   }

   [Fact]
   public void NoFoedselsnummer_JsonDeserialization_ShouldDeserializeNullGracefully()
   {
      // Arrange.
      var json = "{\"Foedselsnummer\":null}";

      // Act.
      var result = JsonSerializer.Deserialize<Foo>(json);

      // Assert.
      result.Should().NotBeNull();
      result!.Foedselsnummer.Should().BeNull();
   }

   [Fact]
   public void NoFoedselsnummer_JsonDeserialization_ShouldThrowKfValidationException_WhenFoedselsnummerIsInvalid()
   {
      // Arrange.
      var json = "{\"Foedselsnummer\":\"13039597140\"}";  // Invalid check digits
      LocalValidationError expected = GetInvalidChecksumResult();

      // Act/assert.
      FluentActions
         .Invoking(() => JsonSerializer.Deserialize<Foo>(json))
         .Should().ThrowExactly<LocalValidationException>()
         .And.ValidationError.Should().BeEquivalentTo(expected);
   }

   #endregion
}
