// Ignore Spelling: Foedselsnummer Nummer

namespace KfAccountNumbers.Tests.Unit.Governmental.Europe;

public class NoFoedselsnummerTests
{
   private const String Valid11CharacterFoedselsnummer = "13029597140";          // Generated by https://norske-testdata.no/fnr/
   private const String AltValid11CharacterFoedselsnummer = "20055029572";
   private const String Valid12CharacterFoedselsnummer = "130295 97140";
   private const String AltValid12CharacterFoedselsnummer = "200550-29572";

   private const String Valid11CharacterDNummer = "66028198842";                 // Generated by https://goof.se/utils/nor-ssn
   private const String AltValid11CharacterDNummer = "49014266312";
   private const String Valid12CharacterDNummer = "660281 98842";
   private const String AltValid12CharacterDNummer = "490142-66312";

   public static TheoryData<String> ValidFoedselsnummerValues =>
   [
      Valid11CharacterFoedselsnummer,
      AltValid11CharacterFoedselsnummer,
      Valid12CharacterFoedselsnummer,
      AltValid12CharacterFoedselsnummer,
   ];

   public static TheoryData<String> ValidDNummerValues =>
   [
      Valid11CharacterDNummer,
      AltValid11CharacterDNummer,
      Valid12CharacterDNummer,
      AltValid12CharacterDNummer,
   ];

   public static TheoryData<String> InvalidLengthValues =>
   [
      "1006127070",        // Length 10
      "100612-707079",    // Length 14
      new String('1', 100) // Very long string
   ];

   public static TheoryData<String> InvalidCharacterValues =>
   [
      "A0061270707",
      "1 061270707",
      "10#61270707",
      "100=1270707",
      "1006B270707",
      "10061C70707",
      "100612D0707",
      "1006127a707",
      "10061270b07",
      "100612707c7",
      "1006127070~",
      "A00612 70707",
      "1 0612 70707",
      "10#612 70707",
      "100=12 70707",
      "1006B2 70707",
      "10061C 70707",
      "100612-D0707",
      "100612-7a707",
      "100612-70b07",
      "100612-707c7",
      "100612-7070~",
   ];

   public static TheoryData<String> InvalidCheckDigitValues =>
   [
      "13039597140",          // 13029597140 with single digit transcription error 2 -> 3
      "20055025972",          // 20055029572 with two digit transposition error 95 -> 59
      "21072551149",          // 21072441149 with two digit twin error 44 -> 55
      "16072996853",          // 16079926853 with jump transposition 992 -> 299
      "13072101223",          // 13072101213 with invalid first check digit 1 -> 2
      "11085149989",          // 11085149980 with invalid second check digit 0 -> 9

      "130395 97140",         // 130295 97140 with single digit transcription error 2 -> 3
      "200550 25972",         // 200550 29572 with two digit transposition error 95 -> 59
      "210725 51149",         // 210724 41149 with two digit twin error 44 -> 55
      "160729 96853",         // 160799 26853 with jump transposition 992 -> 299
      "130721-01223",         // 130721-01213 with invalid first check digit 1 -> 2
      "110851-49989",         // 110851-49980 with invalid second check digit 0 -> 9

      "70066523355",
   ];

   #region Validate Method Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnValidationPassed_WhenValueIsValid(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.ValidationPassed);

   [Theory]
   [ClassData(typeof(StringNullEmptyWhitespaceValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnEmpty_WhenValueIsNullOrEmpty(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.Empty);

   [Theory]
   [MemberData(nameof(InvalidLengthValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidLength_WhenValueHasInvalidLength(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.InvalidLength);

   [Theory]
   [MemberData(nameof(InvalidCharacterValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidCharacter_WhenValueHasNonDigitCharacter(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.InvalidCharacter);

   [Theory]
   [MemberData(nameof(InvalidCheckDigitValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidCheckDigits_WhenValueHasInvalidCheckDigits(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.InvalidCheckDigits);

   [Fact]
   public void BuildFoedselsnummerTest()
   {
      var foedselsnummer = GetFoedselsnummer();

      var x = 0;
   }

   #endregion

   [Fact]
   private static String GetFoedselsnummer(
      String dateOfBirth = "130295",
      String separator = "",
      String individualNumber = "971")
   {
      var value = dateOfBirth + individualNumber;

      var d1 = value[0] - Chars.DigitZero;
      var d2 = value[1] - Chars.DigitZero;
      var d3 = value[2] - Chars.DigitZero;
      var d4 = value[3] - Chars.DigitZero;
      var d5 = value[4] - Chars.DigitZero;
      var d6 = value[5] - Chars.DigitZero;
      var i1 = value[6] - Chars.DigitZero;
      var i2 = value[7] - Chars.DigitZero;
      var i3 = value[8] - Chars.DigitZero;

      var sum1 = (3 * d1) + (7 * d2) + (6 * d3) + (1 * d4) + (8 * d5) + (9 * d6) + (4 * i1) + (5 * i2) + (2 * i3);
      var c1 = (11 - (sum1 % 11)) % 11;
      if (c1 == 10)
      {
         return String.Empty;
      }

      var sum2 = (5 * d1) + (4 * d2) + (3 * d3) + (2 * d4) + (7 * d5) + (6 * d6) + (5 * i1) + (4 * i2) + (3 * i3) + (2 * c1);
      var c2 = (11 - (sum2 % 11)) % 11;
      if (c2 == 10)
      {
         return String.Empty;
      }

      return $"{dateOfBirth}{separator}{individualNumber}{c1}{c2}";
   }
}

