// Ignore Spelling: Foedselsnummer Kf Nummer

#pragma warning disable IDE0008 // Use explicit type

namespace KfAccountNumbers.Tests.Unit.Governmental.Europe;

public class NoFoedselsnummerTests
{
   private const String Valid11CharacterFoedselsnummer = "13029597140";          // Generated by https://norske-testdata.no/fnr/
   private const String AltValid11CharacterFoedselsnummer = "20055029572";
   private const String Valid12CharacterFoedselsnummer = "130295 97140";
   private const String AltValid12CharacterFoedselsnummer = "200550-29572";

   private const String Valid11CharacterDNummer = "53029597134";                 // Above values adjusted for D-nummer
   private const String AltValid11CharacterDNummer = "60055029566";
   private const String Valid12CharacterDNummer = "530295 97134";
   private const String AltValid12CharacterDNummer = "600550-29566";

   private static String GetRawFoedselsnummer(String foedselsnummer)
      => foedselsnummer.Length == 11
         ? foedselsnummer
         : foedselsnummer[..6] + foedselsnummer[7..];

   private static String GetFoedselsnummerWithValidCheckDigits(
      String dateOfBirth = "130295",
      String separator = "",
      String individualNumber = "971")
   {
      var d1 = dateOfBirth[0] - Chars.DigitZero;
      var d2 = dateOfBirth[1] - Chars.DigitZero;
      var d3 = dateOfBirth[2] - Chars.DigitZero;
      var d4 = dateOfBirth[3] - Chars.DigitZero;
      var d5 = dateOfBirth[4] - Chars.DigitZero;
      var d6 = dateOfBirth[5] - Chars.DigitZero;
      var i1 = individualNumber[0] - Chars.DigitZero;
      var i2 = individualNumber[1] - Chars.DigitZero;
      var i3 = individualNumber[2] - Chars.DigitZero;

      var sum1 = (3 * d1) + (7 * d2) + (6 * d3) + (1 * d4) + (8 * d5) + (9 * d6) + (4 * i1) + (5 * i2) + (2 * i3);
      var c1 = (11 - (sum1 % 11)) % 11;
      if (c1 == 10)
      {
         return String.Empty;
      }

      var sum2 = (5 * d1) + (4 * d2) + (3 * d3) + (2 * d4) + (7 * d5) + (6 * d6) + (5 * i1) + (4 * i2) + (3 * i3) + (2 * c1);
      var c2 = (11 - (sum2 % 11)) % 11;
      if (c2 == 10)
      {
         return String.Empty;
      }

      return $"{dateOfBirth}{separator}{individualNumber}{c1}{c2}";
   }

   public static TheoryData<String> ValidFoedselsnummerValues =>
   [
      Valid11CharacterFoedselsnummer,
      AltValid11CharacterFoedselsnummer,
      Valid12CharacterFoedselsnummer,
      AltValid12CharacterFoedselsnummer,
   ];

   public static TheoryData<String> ValidDNummerValues =>
   [
      Valid11CharacterDNummer,
      AltValid11CharacterDNummer,
      Valid12CharacterDNummer,
      AltValid12CharacterDNummer,
   ];

   public static TheoryData<String> ValidSeparators =>
   [
      " ",
      "-",
      "A",
      "z",
      "!",
   ];

   public static TheoryData<String, String> ValidDateOfBirthValues = new()
   {
      // See class documentation on how the individual number and two digit year
      // are used to derive the four digit year. Note also that it is possible for
      // certain combinations to be invalid because of the modulus 11 check digit. In
      // those cases, the rows are duplicated and the day is adjusted in one and the
      // individual number is adjusted in the other

      // Minimum valid date = Jan 1, 1854
      // Maximum valid date = Dec 31, 2039

      // Rule 1 - individual number >= 500 and <= 749 and year >= 54 - century = 1800's
      { "010154", "500" },       // minimum 6 digit date and minimum individual number
      { "010154", "749" },       // minimum 6 digit date and maximum individual number
      { "311299", "500" },       // maximum 6 digit date and minimum individual number
      { "301299", "749" },       // maximum 6 digit date and maximum individual number (311299 749 adjusted because of check digits)
      { "311299", "748" },       // maximum 6 digit date and maximum individual number  "

      // Rule 2 - individual number < 500, year not considered - century = 1900's
      { "020100", "000" },       // minimum 6 digit date and minimum individual number (010100 000 adjusted because of check digits)
      { "010100", "001" },       // minimum 6 digit date and minimum individual number  "
      { "010100", "499" },       // minimum 6 digit date and maximum individual number  
      { "301299", "000" },       // maximum 6 digit date and minimum individual number (311299 000 adjusted because of check digits)
      { "311299", "001" },       // maximum 6 digit date and minimum individual number  "
      { "311299", "499" },       // maximum 6 digit date and maximum individual number  

      // Rule 3 - individual number >= 900 and year >= 40 - century = 1900's
      { "010140", "900" },       // minimum 6 digit date and minimum individual number
      { "010140", "999" },       // minimum 6 digit date and maximum individual number  
      { "311299", "900" },       // maximum 6 digit date and minimum individual number
      { "301299", "999" },       // maximum 6 digit date and maximum individual number (311299 999 adjusted because of check digits)
      { "311299", "998" },       // maximum 6 digit date and maximum individual number  "

      // Rule 4 - individual number >= 500 and year <= 39 - century - 2000's
      { "010100", "500" },       // minimum 6 digit date and minimum individual number
      { "010100", "999" },       // minimum 6 digit date and maximum individual number
      { "311239", "500" },       // maximum 6 digit date and minimum individual number
      { "311239", "999" },       // maximum 6 digit date and maximum individual number

      { "310104", "501" },       // maximum days for January, any year
      { "280201", "234" },       // maximum days for Feburary, non-leap year
      { "290204", "234" },       // maximum days for Feburary, leap year
      { "290200", "500" },       // maximum days for Feburary, leap year (2000 is leap-year)
      { "310304", "501" },       // maximum days for March, any year
      { "300404", "499" },       // maximum days for April, any year
      { "310504", "501" },       // maximum days for May, any year
      { "300604", "500" },       // maximum days for June, any year
      { "310704", "501" },       // maximum days for July, any year
      { "310804", "501" },       // maximum days for August, any year
      { "300904", "500" },       // maximum days for September, any year
      { "311004", "501" },       // maximum days for October, any year
      { "301104", "499" },       // maximum days for November, any year
      { "311204", "500" },       // maximum days for December, any year

      // Repeat for D-nummer
      // Rule 1 - individual number >= 500 and <= 749 and year >= 54 - century = 1800's
      { "410154", "500" },       // minimum 6 digit date and minimum individual number
      { "410154", "749" },       // minimum 6 digit date and maximum individual number
      { "701299", "500" },       // maximum 6 digit date and minimum individual number (711299 500 adjusted because of check digits)
      { "711299", "501" },       // maximum 6 digit date and minimum individual number  "
      { "711299", "749" },       // maximum 6 digit date and maximum individual number 

      // Rule 2 - individual number < 500, year not considered - century = 1900's
      { "410100", "000" },       // minimum 6 digit date and minimum individual number
      { "410100", "499" },       // minimum 6 digit date and maximum individual number  
      { "711299", "000" },       // maximum 6 digit date and minimum individual number
      { "711299", "499" },       // maximum 6 digit date and maximum individual number  

      // Rule 3 - individual number >= 900 and year >= 40 - century = 1900's
      { "410140", "900" },       // minimum 6 digit date and minimum individual number
      { "410140", "999" },       // minimum 6 digit date and maximum individual number  
      { "711299", "900" },       // maximum 6 digit date and minimum individual number
      { "711299", "999" },       // maximum 6 digit date and maximum individual number

      // Rule 4 - individual number >= 500 and year <= 39 - century - 2000's
      { "410100", "500" },       // minimum 6 digit date and minimum individual number
      { "410100", "999" },       // minimum 6 digit date and maximum individual number
      { "711239", "500" },       // maximum 6 digit date and minimum individual number
      { "711239", "999" },       // maximum 6 digit date and maximum individual number

      { "710104", "501" },       // maximum days for January, any year
      { "680201", "234" },       // maximum days for Feburary, non-leap year
      { "690204", "234" },       // maximum days for Feburary, leap year
      { "690200", "500" },       // maximum days for Feburary, leap year (2000 is leap-year)
      { "710304", "500" },       // maximum days for March, any year
      { "700404", "499" },       // maximum days for April, any year
      { "710504", "501" },       // maximum days for May, any year
      { "700604", "500" },       // maximum days for June, any year
      { "710704", "501" },       // maximum days for July, any year
      { "710804", "501" },       // maximum days for August, any year
      { "700904", "500" },       // maximum days for September, any year
      { "711004", "501" },       // maximum days for October, any year
      { "701104", "499" },       // maximum days for November, any year
      { "711204", "500" },       // maximum days for December, any year
   };

   public static TheoryData<String> InvalidLengthValues =>
   [
      "1006127070",        // Length 10
      "100612-707079",     // Length 14
      new String('1', 100) // Very long string
   ];

   public static TheoryData<String> InvalidCharacterValues =>
   [
      "A0061270707",
      "1 061270707",
      "10#61270707",
      "100=1270707",
      "1006B270707",
      "10061C70707",
      "100612D0707",
      "1006127a707",
      "10061270b07",
      "100612707c7",
      "1006127070~",
      "A00612 70707",
      "1 0612 70707",
      "10#612 70707",
      "100=12 70707",
      "1006B2 70707",
      "10061C 70707",
      "100612-D0707",
      "100612-7a707",
      "100612-70b07",
      "100612-707c7",
      "100612-7070~",
   ];

   public static TheoryData<String> InvalidCheckDigitValues =>
   [
      "13039597140",          // 13029597140 with single digit transcription error 2 -> 3
      "20055025972",          // 20055029572 with two digit transposition error 95 -> 59
      "21072551149",          // 21072441149 with two digit twin error 44 -> 55
      "16072996853",          // 16079926853 with jump transposition 992 -> 299
      "13072101223",          // 13072101213 with invalid first check digit 1 -> 2
      "11085149989",          // 11085149980 with invalid second check digit 0 -> 9

      "130395 97140",         // 130295 97140 with single digit transcription error 2 -> 3
      "200550 25972",         // 200550 29572 with two digit transposition error 95 -> 59
      "210725 51149",         // 210724 41149 with two digit twin error 44 -> 55
      "160729 96853",         // 160799 26853 with jump transposition 992 -> 299
      "130721-01223",         // 130721-01213 with invalid first check digit 1 -> 2
      "110851-49989",         // 110851-49980 with invalid second check digit 0 -> 9
   ];

   public static TheoryData<String> InvalidSeparators =>
   [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
   ];

   public static TheoryData<String, String> InvalidDateOfBirthValues = new()
   {
      // See ValidDateOfBirthValues above for more info on design of date of birth/individual number pairs.

      // Rule 1 - individual number >= 500 and <= 749 and year >= 54 - century = 1800's
      { "010153", "500" },       // minimum 6 digit date and minimum individual number - less than minimum valid date
      { "010153", "749" },       // minimum 6 digit date and maximum individual number - "

      // Rule 2 - individual number < 500, year not considered - century = 1900's
      // No valid 6 digit dates fall outside valid range

      // Rule 3 - individual number >= 900 and year >= 40 - century = 1900's
      // No valid 6 digit dates fall outside valid range

      // Rule 4 - individual number >= 500 and year <= 39 - century - 2000's
      { "010140", "500" },       // minimum 6 digit date and minimum individual number - greater than maximum valid date
      { "010140", "899" },       // minimum 6 digit date and maximum individual number - "

      { "010004", "500" },       // month = 0
      { "011304", "500" },       // month = 13
      { "000104", "500" },       // days = 0
      { "320104", "500" },       // Invalid day of month for January, any year
      { "290201", "502" },       // Invalid day of for Feburary, non-leap year
      { "300204", "501" },       // Invalid day of for Feburary, leap year
      { "300200", "500" },       // Invalid day of for Feburary, leap year (2000 is leap-year)
      { "320304", "500" },       // Invalid day of for March, any year
      { "310404", "502" },       // Invalid day of for April, any year
      { "320504", "500" },       // Invalid day of for May, any year
      { "310604", "501" },       // Invalid day of for June, any year
      { "320704", "500" },       // Invalid day of for July, any year
      { "320804", "500" },       // Invalid day of for August, any year
      { "310904", "501" },       // Invalid day of for September, any year
      { "321004", "500" },       // Invalid day of for October, any year
      { "311104", "500" },       // Invalid day of for November, any year
      { "321204", "500" },       // Invalid day of for December, any year

      // Repeat for D-nummer
      // Rule 1 - individual number >= 500 and <= 749 and year >= 54 - century = 1800's
      { "410153", "500" },       // minimum 6 digit date and minimum individual number - less than minimum valid date
      { "410153", "749" },       // minimum 6 digit date and maximum individual number - "

      // Rule 2 - individual number < 500, year not considered - century = 1900's
      // No valid 6 digit dates fall outside valid range

      // Rule 3 - individual number >= 900 and year >= 40 - century = 1900's
      // No valid 6 digit dates fall outside valid range

      // Rule 4 - individual number >= 500 and year <= 39 - century - 2000's
      { "410140", "501" },       // minimum 6 digit date and minimum individual number - greater than maximum valid date
      { "410140", "899" },       // minimum 6 digit date and maximum individual number - "

      { "410004", "500" },       // Invalid month = 0
      { "411304", "500" },       // Invalid month = 13
      { "400104", "500" },       // Invalid day = 0
      { "720104", "500" },       // Invalid day of month for January, any year
      { "690201", "500" },       // Invalid day of for Feburary, non-leap year
      { "700204", "500" },       // Invalid day of for Feburary, leap year
      { "700200", "500" },       // Invalid day of for Feburary, leap year (2000 is leap-year)
      { "720304", "500" },       // Invalid day of for March, any year
      { "710404", "500" },       // Invalid day of for April, any year
      { "720504", "500" },       // Invalid day of for May, any year
      { "710604", "500" },       // Invalid day of for June, any year
      { "720704", "500" },       // Invalid day of for July, any year
      { "720804", "500" },       // Invalid day of for August, any year
      { "710904", "500" },       // Invalid day of for September, any year
      { "721004", "500" },       // Invalid day of for October, any year
      { "711104", "500" },       // Invalid day of for November, any year
      { "721204", "500" },       // Invalid day of for December, any year

      // H nummer (40 added to month) not currently supported
      { "014154", "500" },

      // FH nummer (starts with 8 or 9) not currently supported
      { "810100", "501" },
      { "910100", "501" },
   };

   #region Constructor Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_Constructor_ShouldCreateInstance_WhenValueIsValid(String value)
   {
      // Arrange.
      var expected = GetRawFoedselsnummer(value);

      // Act.
      var sut = new NoFoedselsnummer(value);

      // Assert.
      sut.Should().NotBeNull();
      sut.Value.Should().Be(expected);
   }

   [Theory]
   [MemberData(nameof(ValidSeparators))]
   public void NoFoedselsnummer_Constructor_ShouldCreateInstance_WhenValueHasValidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      var expected = GetRawFoedselsnummer(value);

      // Act.
      var sut = new NoFoedselsnummer(value);

      // Assert.
      sut.Should().NotBeNull();
      sut.Value.Should().Be(expected);
   }

   [Theory]
   [MemberData(nameof(ValidDateOfBirthValues))]
   public void NoFoedselsnummer_Constructor_ShouldCreateInstance_WhenValueHasValidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var expected = GetRawFoedselsnummer(value);

      // Act.
      var sut = new NoFoedselsnummer(value);

      // Assert.
      sut.Should().NotBeNull();
      sut.Value.Should().Be(expected);
   }

   [Theory]
   [ClassData(typeof(StringNullEmptyWhitespaceValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueIsNullOrEmpty(String value)
      => FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().Throw<KfValidationException<NoFoedselsnummerValidationResult>>()
         .WithMessage(Messages.NoFoedselsnummerEmpty + "*")
         .And.ValidationResult.Should().Be(NoFoedselsnummerValidationResult.Empty);

   [Theory]
   [MemberData(nameof(InvalidLengthValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasInvalidLength(String value)
      => FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().Throw<KfValidationException<NoFoedselsnummerValidationResult>>()
         .WithMessage(Messages.NoFoedselsnummerInvalidLength + "*")
         .And.ValidationResult.Should().Be(NoFoedselsnummerValidationResult.InvalidLength);

   [Theory]
   [MemberData(nameof(InvalidCharacterValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasNonDigitCharacter(String value)
      => FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().Throw<KfValidationException<NoFoedselsnummerValidationResult>>()
         .WithMessage(Messages.NoFoedselsnummerInvalidCharacter + "*")
         .And.ValidationResult.Should().Be(NoFoedselsnummerValidationResult.InvalidCharacter);

   [Theory]
   [MemberData(nameof(InvalidCheckDigitValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasCheckDigits(String value)
      => FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().Throw<KfValidationException<NoFoedselsnummerValidationResult>>()
         .WithMessage(Messages.NoFoedselsnummerInvalidCheckDigits + "*")
         .And.ValidationResult.Should().Be(NoFoedselsnummerValidationResult.InvalidCheckDigits);

   [Theory]
   [MemberData(nameof(InvalidSeparators))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);

      // Act/assert.
      FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().Throw<KfValidationException<NoFoedselsnummerValidationResult>>()
         .WithMessage(Messages.NoFoedselsnummerInvalidSeparator + "*")
         .And.ValidationResult.Should().Be(NoFoedselsnummerValidationResult.InvalidSeparator);
   }

   [Theory]
   [MemberData(nameof(InvalidDateOfBirthValues))]
   public void NoFoedselsnummer_Constructor_ShouldThrowKfValidationException_WhenValueHasInvalidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);

      // Act/assert.
      FluentActions
         .Invoking(() => new NoFoedselsnummer(value))
         .Should().Throw<KfValidationException<NoFoedselsnummerValidationResult>>()
         .WithMessage(Messages.NoFoedselsnummerInvalidDateOfBirth + "*")
         .And.ValidationResult.Should().Be(NoFoedselsnummerValidationResult.InvalidDateOfBirth);
   }

   #endregion

   #region DateOfBirth Property Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   // See ValidDateOfBirthValues property for rules associated with the individual numbers
   [InlineData("010154", "500", "18540101")]       // Rule 1, January 1, 1854
   [InlineData("311299", "748", "18991231")]       // Rule 1, December 31, 1899
   [InlineData("010100", "001", "19000101")]       // Rule 2, January 1, 1900
   [InlineData("311299", "499", "19991231")]       // Rule 2, December 31, 1999
   [InlineData("010140", "900", "19400101")]       // Rule 3, January 1, 1940
   [InlineData("311299", "998", "19991231")]       // Rule 3, December 31, 1999
   [InlineData("010100", "500", "20000101")]       // Rule 4, January 1, 2000
   [InlineData("311239", "999", "20391231")]       // Rule 4, December 31, 2039
   [InlineData("290296", "501", "18960229")]       // Feburary 29, 1896 - leap year
   [InlineData("280200", "235", "19000228")]       // Feburary 28, 1900 - non leap year
   [InlineData("290248", "318", "19480229")]       // Feburary 29, 1948 - leap year
   [InlineData("290200", "601", "20000229")]       // Feburary 29, 2000 - leap year

   // D-nummer values
   [InlineData("410154", "500", "18540101")]       // Rule 1, January 1, 1854
   [InlineData("711299", "748", "18991231")]       // Rule 1, December 31, 1899
   [InlineData("410100", "001", "19000101")]       // Rule 2, January 1, 1900
   [InlineData("711299", "499", "19991231")]       // Rule 2, December 31, 1999
   [InlineData("410140", "900", "19400101")]       // Rule 3, January 1, 1940
   [InlineData("711299", "998", "19991231")]       // Rule 3, December 31, 1999
   [InlineData("410100", "500", "20000101")]       // Rule 4, January 1, 2000
   [InlineData("711239", "999", "20391231")]       // Rule 4, December 31, 2039
   [InlineData("690296", "501", "18960229")]       // Feburary 29, 1896 - leap year
   [InlineData("680200", "235", "19000228")]       // Feburary 28, 1900 - non leap year
   [InlineData("690248", "318", "19480229")]       // Feburary 29, 1948 - leap year
   [InlineData("690200", "601", "20000229")]       // Feburary 29, 2000 - leap year
   public void NoFoedselsnummer_DateOfBirth_ShouldReturnExpectedValue(
      String dateOfBirth,
      String individualNumber,
      String expectedDateOfBirth)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var sut = new NoFoedselsnummer(value);
      var expected = DateOnly.ParseExact(
         expectedDateOfBirth,
         "yyyyMMdd",
         System.Globalization.CultureInfo.InvariantCulture);

      // Act/assert.
      sut.DateOfBirth.Should().Be(expected);
   }

   #endregion

   #region Gender Property Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [InlineData("540", BinaryGender.Female)]
   [InlineData("541", BinaryGender.Male)]
   [InlineData("542", BinaryGender.Female)]
   [InlineData("543", BinaryGender.Male)]
   [InlineData("544", BinaryGender.Female)]
   [InlineData("545", BinaryGender.Male)]
   [InlineData("546", BinaryGender.Female)]
   [InlineData("547", BinaryGender.Male)]
   [InlineData("648", BinaryGender.Female)]     // 5 changed to 6 because of modulus 11 check digits
   [InlineData("549", BinaryGender.Male)]
   public void NoFoedselsnummer_Gender_ShouldReturnExpectedValue(
      String individualNumber,
      BinaryGender expectedGender)
   {
      // Arrange.
      var personnummer = GetFoedselsnummerWithValidCheckDigits(individualNumber: individualNumber);
      var sut = new NoFoedselsnummer(personnummer);

      // Act/assert.
      sut.Gender.Should().Be(expectedGender);
   }

   #endregion

   #region IdentifierType Property Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [InlineData("010154", "500")]
   [InlineData("311239", "999")]
   public void NoFoedselsnummer_IdentifierType_ShouldReturnExpectedValue_WhenValueIsFoedselsnummer(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var sut = new NoFoedselsnummer(value);

      // Act/assert.
      sut.IdentifierType.Should().Be(NoIdentifierType.Foedselsnummer);
   }

   [Theory]
   [InlineData("410154", "500")]
   [InlineData("711239", "999")]
   public void NoFoedselsnummer_IdentifierType_ShouldReturnExpectedValue_WhenValueIsDNummer(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var sut = new NoFoedselsnummer(value);

      // Act/assert.
      sut.IdentifierType.Should().Be(NoIdentifierType.DNummer);
   }

   #endregion

   #region Value Property Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [InlineData(Valid11CharacterFoedselsnummer, Valid11CharacterFoedselsnummer)]
   [InlineData(Valid12CharacterFoedselsnummer, Valid11CharacterFoedselsnummer)]
   [InlineData(Valid11CharacterDNummer, Valid11CharacterDNummer)]
   [InlineData(Valid12CharacterDNummer, Valid11CharacterDNummer)]
   public void NoFoedselsnummer_Value_ShouldReturnValidatedFoedselsnummer(
      String value,
      String expected)
   {
      // Arrange.
      var sut = new NoFoedselsnummer(value);

      // Act/assert.
      sut.Value.Should().Be(expected);
   }

   #endregion

   #region Equality Operator Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_EqualityOperator_ShouldReturnTrue_WhenValuesAreEqual()
   {
      // Arrange.
      var foedselsnummer1 = new NoFoedselsnummer(Valid11CharacterFoedselsnummer);
      var foedselsnummer2 = new NoFoedselsnummer(Valid11CharacterFoedselsnummer);

      // Act/assert.
      (foedselsnummer1 == foedselsnummer2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_EqualityOperator_ShouldReturnFalse_WhenValuesAreNotEqual()
   {
      // Arrange.
      var foedselsnummer1 = new NoFoedselsnummer(Valid11CharacterFoedselsnummer);
      var foedselsnummer2 = new NoFoedselsnummer(AltValid11CharacterFoedselsnummer);

      // Act/assert.
      (foedselsnummer1 == foedselsnummer2).Should().BeFalse();
   }

   [Fact]
   public void NoFoedselsnummer_EqualityOperator_ShouldReturnTrue_WhenValuesHaveDifferentLengths()
   {
      // Arrange. 11 and 12 character versions for same person should still be equal.
      var foedselsnummer1 = new NoFoedselsnummer(Valid11CharacterFoedselsnummer);
      var foedselsnummer2 = new NoFoedselsnummer(Valid12CharacterFoedselsnummer);

      // Act/assert.
      (foedselsnummer1 == foedselsnummer2).Should().BeTrue();
   }

   #endregion

   #region Inequality Operator Tests
   // ==========================================================================
   // ==========================================================================

   [Fact]
   public void NoFoedselsnummer_InequalityOperator_ShouldReturnTrue_WhenValuesAreNotEqual()
   {
      // Arrange.
      var foedselsnummer1 = new NoFoedselsnummer(Valid11CharacterFoedselsnummer);
      var foedselsnummer2 = new NoFoedselsnummer(AltValid11CharacterFoedselsnummer);

      // Act/assert.
      (foedselsnummer1 != foedselsnummer2).Should().BeTrue();
   }

   [Fact]
   public void NoFoedselsnummer_InequalityOperator_ShouldReturnFalse_WhenValuesHaveDifferentLengths()
   {
      // Arrange. 11 and 12 character versions for same person should still be equal.
      var foedselsnummer1 = new NoFoedselsnummer(Valid11CharacterFoedselsnummer);
      var foedselsnummer2 = new NoFoedselsnummer(Valid12CharacterFoedselsnummer);

      // Act/assert.
      (foedselsnummer1 != foedselsnummer2).Should().BeFalse();
   }

   [Fact]
   public void NoFoedselsnummer_InequalityOperator_ShouldReturnFalse_WhenValuesAreEqual()
   {
      // Arrange.
      var foedselsnummer1 = new NoFoedselsnummer(Valid11CharacterFoedselsnummer);
      var foedselsnummer2 = new NoFoedselsnummer(Valid11CharacterFoedselsnummer);

      // Act/assert.
      (foedselsnummer1 != foedselsnummer2).Should().BeFalse();
   }

   #endregion

   #region Create Method Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_Create_ShouldCreateInstance_WhenValueIsValid(String value)
   {
      // Arrange.
      var expectedValue = new NoFoedselsnummer(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeTrue();
      result.Value.Should().BeEquivalentTo(expectedValue);
      result.ValidationFailure.Should().Be(default);
   }

   [Theory]
   [MemberData(nameof(ValidSeparators))]
   public void NoFoedselsnummer_Create_ShouldCreateInstance_WhenValueHasValidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);
      var expectedValue = new NoFoedselsnummer(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeTrue();
      result.Value.Should().BeEquivalentTo(expectedValue);
      result.ValidationFailure.Should().Be(default);
   }

   [Theory]
   [MemberData(nameof(ValidDateOfBirthValues))]
   public void NoFoedselsnummer_Create_ShouldCreateInstance_WhenValueHasValidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);
      var expectedValue = new NoFoedselsnummer(value);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeTrue();
      result.Value.Should().BeEquivalentTo(expectedValue);
      result.ValidationFailure.Should().Be(default);
   }

   [Theory]
   [ClassData(typeof(StringNullEmptyWhitespaceValues))]
   public void NoFoedselsnummer_Create_ShouldReturnEmptyValidationResult_WhenValueIsEmpty(String value)
   {
      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeFalse();
      result.Value.Should().Be(null);
      result.ValidationFailure.Should().Be(NoFoedselsnummerValidationResult.Empty);
   }

   [Theory]
   [MemberData(nameof(InvalidLengthValues))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidLengthValidationResult_WhenValueHasInvalidLength(String value)
   {
      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeFalse();
      result.Value.Should().Be(null);
      result.ValidationFailure.Should().Be(NoFoedselsnummerValidationResult.InvalidLength);
   }

   [Theory]
   [MemberData(nameof(InvalidCharacterValues))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidCharacterValidationResult_WhenValueHasNonDigitCharacter(String value)
   {
      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeFalse();
      result.Value.Should().Be(null);
      result.ValidationFailure.Should().Be(NoFoedselsnummerValidationResult.InvalidCharacter);
   }

   [Theory]
   [MemberData(nameof(InvalidCheckDigitValues))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidCheckDigitsValidationResult_WhenValueHasInvalidCheckDigits(String value)
   {
      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeFalse();
      result.Value.Should().Be(null);
      result.ValidationFailure.Should().Be(NoFoedselsnummerValidationResult.InvalidCheckDigits);
   }

   [Theory]
   [MemberData(nameof(InvalidSeparators))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidSeparatorValidationResult_WhenValueHasInvalidCSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeFalse();
      result.Value.Should().Be(null);
      result.ValidationFailure.Should().Be(NoFoedselsnummerValidationResult.InvalidSeparator);
   }

   [Theory]
   [MemberData(nameof(InvalidDateOfBirthValues))]
   public void NoFoedselsnummer_Create_ShouldReturnInvalidDateOfBirthValidationResult_WhenValueHasInvalidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);

      // Act.
      var result = NoFoedselsnummer.Create(value);

      // Assert.
      result.Should().NotBeNull();
      result.IsSuccess.Should().BeFalse();
      result.Value.Should().Be(null);
      result.ValidationFailure.Should().Be(NoFoedselsnummerValidationResult.InvalidDateOfBirth);
   }

   #endregion

   #region Validate Method Tests
   // ==========================================================================
   // ==========================================================================

   [Theory]
   [MemberData(nameof(ValidFoedselsnummerValues))]
   [MemberData(nameof(ValidDNummerValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnValidationPassed_WhenValueIsValid(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.ValidationPassed);

   [Theory]
   [MemberData(nameof(ValidSeparators))]
   public void NoFoedselsnummer_Validate_ShouldReturnValidationPassed_WhenValueHasValidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);

      // Act/assert.
      NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.ValidationPassed);
   }

   [Theory]
   [MemberData(nameof(ValidDateOfBirthValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnValidationPassed_WhenValueHasValidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);

      // Act/assert.
      NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.ValidationPassed);
   }

   [Theory]
   [ClassData(typeof(StringNullEmptyWhitespaceValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnEmpty_WhenValueIsNullOrEmpty(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.Empty);

   [Theory]
   [MemberData(nameof(InvalidLengthValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidLength_WhenValueHasInvalidLength(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.InvalidLength);

   [Theory]
   [MemberData(nameof(InvalidCharacterValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidCharacter_WhenValueHasNonDigitCharacter(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.InvalidCharacter);

   [Theory]
   [MemberData(nameof(InvalidCheckDigitValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidCheckDigits_WhenValueHasInvalidCheckDigits(String value)
      => NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.InvalidCheckDigits);

   [Theory]
   [MemberData(nameof(InvalidSeparators))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidSeparator_WhenValueHasInvalidSeparator(String separator)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(separator: separator);

      // Act/assert.
      NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.InvalidSeparator);
   }

   [Theory]
   [MemberData(nameof(InvalidDateOfBirthValues))]
   public void NoFoedselsnummer_Validate_ShouldReturnInvalidDateOfBirth_WhenValueHasInvalidDateOfBirth(
      String dateOfBirth,
      String individualNumber)
   {
      // Arrange.
      var value = GetFoedselsnummerWithValidCheckDigits(
         dateOfBirth: dateOfBirth,
         individualNumber: individualNumber);

      // Act/assert.
      NoFoedselsnummer.Validate(value).Should().Be(NoFoedselsnummerValidationResult.InvalidDateOfBirth);
   }

   #endregion
}

